Repository helm/helm-www, pull requests merged in 2019-09, with the labels that each got.

#275 Make vanity url usable by chartmuseum
  content/code/chartmuseum.md
Labels: size/XS

#276 feat: Add documentation about the new crds directory.
  content/docs/topics/charts.md
Labels: docs, size/M

#269 fix sticky banner for v2 <-> v3 site links
  config.toml
  themes/helm/assets/sass/docs-home.scss
  themes/helm/assets/sass/docs-responsive.scss
  themes/helm/assets/sass/docs-sidebar.scss
  themes/helm/assets/sass/docs-topbar.scss
  themes/helm/assets/sass/helm-blog.scss
  themes/helm/assets/sass/helm-home.scss
  themes/helm/layouts/blog/list.html
  themes/helm/layouts/blog/single.html
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/index.html
  themes/helm/layouts/partials/banner.html
  themes/helm/layouts/partials/nav.html
  themes/helm/layouts/partials/topbar.html
Labels: size/L

#277 docs(bug): correct the v2 current version
  config.toml
  themes/helm/assets/sass/docs-topbar.scss
  themes/helm/layouts/partials/nav.html
Labels: awaiting review, bug, size/XS

#279 change to apache2, fix copyright
  LICENSE
Labels: size/L

#280 Update helm-home.scss
  themes/helm/assets/sass/helm-home.scss
Labels: size/XS

#282 post: How to migrate from Helm v2 to Helm v3
  content/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
Labels: size/L

#281 Improve contrast accessibility of contribute button
  themes/helm/assets/sass/docs-sidebar.scss
Labels: size/XS

#285 Post: update migrate-from-helm-v2-to-helm-v3 with clean up feature
  content/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
Labels: size/M

#286 Updates documentation for automatically rolling deployments
  content/docs/howto/charts_tips_and_tricks.md
Labels: size/M

#287 Add migration documentation
  content/docs/intro/v2_v3_migration.md
Labels: size/M

#289 docs(topics): add details about the LICENSE file
  content/docs/topics/charts.md
Labels: size/S

#290 Fix typos in v2–v3 migration documentation
  content/docs/intro/v2_v3_migration.md
Labels: size/XS

#291 Fix broken links to docs pages
  content/docs/faq.md
Labels: size/XS

#292 Update v2_v3_migration doc with link to migration blog post
  content/docs/intro/v2_v3_migration.md
Labels: size/XS

#293 Update 2019-09-11-migrate-from-helm-v2-to-helm-v3
  content/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
Labels: size/M

#294 fix: Update docs to remove 'helm init' and add 'helm repo add'
  content/docs/intro/quickstart.md
Labels: size/S

#295 fix: remove references to helm init
  content/docs/community/release_checklist.md
  content/docs/faq.md
  content/docs/glossary.md
  content/docs/intro/install.md
  content/docs/topics/plugins.md
Labels: size/M
