Repository helm/helm-www, pull requests merged in 2019-10, with the labels that each got.

#296 fix: updated references about HELM_HOME to use XDG_*
  content/docs/faq.md
  content/docs/topics/chart_repository.md
  content/docs/topics/charts.md
  content/docs/topics/plugins.md
Labels: size/S

#302 Updating versions mentioned on website
  config.toml
  themes/helm/layouts/partials/banner.html
Labels: size/XS

#305 Add vanity url for helm v3 with Go modules
  content/code/helm-v3.md
Labels: size/XS

#304 Helm 3: reference Helm 3 rather than specific version
  config.toml
  themes/helm/layouts/partials/banner.html
Labels: size/S

#303 Helm 2: reference Helm 3 rather than the "latest" release
  config.toml
  themes/helm/layouts/partials/banner.html
Labels: size/XS

#306 fix: Update docs to include generate-name argument
  content/docs/intro/quickstart.md
Labels: size/XS

#309 feat(rbac): add Role-based Access Control documentation
  content/docs/intro/rbac.md
Labels: size/L

#311 Improve documentation consistency
  README.md
  content/docs/community/developers.md
  content/docs/faq.md
  content/docs/howto/charts_tips_and_tricks.md
  content/docs/intro/install.md
  content/docs/intro/rbac.md
  content/docs/intro/using_helm.md
  content/docs/topics/chart_best_practices/dependencies.md
  content/docs/topics/chart_best_practices/pods.md
  content/docs/topics/chart_best_practices/templates.md
  content/docs/topics/chart_repository.md
  content/docs/topics/chart_template_guide/accessing_files.md
  content/docs/topics/chart_template_guide/builtin_objects.md
  content/docs/topics/chart_template_guide/control_structures.md
  content/docs/topics/chart_template_guide/debugging.md
  content/docs/topics/chart_template_guide/functions_and_pipelines.md
  content/docs/topics/chart_template_guide/named_templates.md
  content/docs/topics/chart_template_guide/subcharts_and_globals.md
  content/docs/topics/chart_template_guide/values_files.md
  content/docs/topics/chart_template_guide/variables.md
  content/docs/topics/chart_template_guide/yaml_techniques.md
  content/docs/topics/chart_tests.md
  content/docs/topics/charts.md
  content/docs/topics/charts_hooks.md
  content/docs/topics/plugins.md
  content/docs/topics/provenance.md
  content/docs/topics/registries.md
Labels: size/L

#313 dev(chore): delete brigade.js
  brigade.js
Labels: awaiting review, size/M

#315 fix: update dev-v3 to master branch
  content/code/helm.md
  content/docs/topics/charts.md
Labels: size/XS

#307 Fix broken link in Quicklinks
  themes/helm/layouts/docs/list.html
Labels: size/XS

#317 feat(blog): Helm 2.15.0 Released
  content/blog/2019-10-22-helm-2150-released.md
Labels: size/M

#323 Updates FAQ and Glossary pages with the most recent information
  content/docs/faq.md
  content/docs/glossary.md
Labels: size/M

#324 Formats all docs to use same wrapping
  content/docs/_index.md
  content/docs/community/_index.md
  content/docs/community/developers.md
  content/docs/community/history.md
  content/docs/community/related.md
  content/docs/community/release_checklist.md
  content/docs/faq.md
  content/docs/glossary.md
  content/docs/howto/_index.md
  content/docs/howto/chart_repository_sync_example.md
  content/docs/howto/charts_tips_and_tricks.md
  content/docs/intro/getting_started.md
  content/docs/intro/install.md
  content/docs/intro/kubernetes_distros.md
  content/docs/intro/quickstart.md
  content/docs/intro/rbac.md
  content/docs/intro/using_helm.md
  content/docs/intro/v2_v3_migration.md
  content/docs/topics/_index.md
  content/docs/topics/architecture.md
  content/docs/topics/chart_best_practices/_index.md
  content/docs/topics/chart_best_practices/conventions.md
  content/docs/topics/chart_best_practices/custom_resource_definitions.md
  content/docs/topics/chart_best_practices/dependencies.md
  content/docs/topics/chart_best_practices/labels.md
  content/docs/topics/chart_best_practices/pods.md
  content/docs/topics/chart_best_practices/rbac.md
  content/docs/topics/chart_best_practices/templates.md
  content/docs/topics/chart_best_practices/values.md
  content/docs/topics/chart_repository.md
  content/docs/topics/chart_template_guide/_index.md
  content/docs/topics/chart_template_guide/accessing_files.md
  content/docs/topics/chart_template_guide/builtin_objects.md
  content/docs/topics/chart_template_guide/control_structures.md
  content/docs/topics/chart_template_guide/data_types.md
  content/docs/topics/chart_template_guide/debugging.md
  content/docs/topics/chart_template_guide/functions_and_pipelines.md
  content/docs/topics/chart_template_guide/named_templates.md
  content/docs/topics/chart_template_guide/notes_files.md
  content/docs/topics/chart_template_guide/subcharts_and_globals.md
  content/docs/topics/chart_template_guide/values_files.md
  content/docs/topics/chart_template_guide/variables.md
  content/docs/topics/chart_template_guide/yaml_techniques.md
  content/docs/topics/chart_tests.md
  content/docs/topics/charts.md
  content/docs/topics/charts_hooks.md
  content/docs/topics/plugins.md
  content/docs/topics/provenance.md
  content/docs/topics/registries.md
Labels: size/XXL

#325 Updates Kubernetes distros to match v2
  content/docs/glossary.md
  content/docs/intro/kubernetes_distros.md
Labels: size/M

#329 Adding post on symlink vulnerability
  content/blog/2019-10-30-helm-symlink-security-notice.md
Labels: size/M
