Repository helm/helm-www, pull requests merged in 2019-07, with the labels that each got.

#228 add an OWNERS file
  OWNERS
Labels: awaiting review, size/XS

#232 bump npm dependancies
  package.json
  yarn.lock
Labels: dependencies, size/L

#236 [#229] rewrite fix for chart development url
  gulpfile.js
Labels: size/XS

#234 refactor dependencies in build pipeline
  .gitignore
  gulpfile.js
  package.json
  themes/helm/static/src/sass/foundation/foundation.scss
  themes/helm/static/src/sass/foundation/foundation/_functions.scss
  themes/helm/static/src/sass/foundation/foundation/_settings.scss
  themes/helm/static/src/sass/foundation/foundation/components/_accordion.scss
  themes/helm/static/src/sass/foundation/foundation/components/_alert-boxes.scss
  themes/helm/static/src/sass/foundation/foundation/components/_block-grid.scss
  themes/helm/static/src/sass/foundation/foundation/components/_breadcrumbs.scss
  themes/helm/static/src/sass/foundation/foundation/components/_button-groups.scss
  themes/helm/static/src/sass/foundation/foundation/components/_buttons.scss
  themes/helm/static/src/sass/foundation/foundation/components/_clearing.scss
  themes/helm/static/src/sass/foundation/foundation/components/_dropdown-buttons.scss
  themes/helm/static/src/sass/foundation/foundation/components/_dropdown.scss
  themes/helm/static/src/sass/foundation/foundation/components/_flex-video.scss
  themes/helm/static/src/sass/foundation/foundation/components/_forms.scss
  themes/helm/static/src/sass/foundation/foundation/components/_global.scss
  themes/helm/static/src/sass/foundation/foundation/components/_grid.scss
  themes/helm/static/src/sass/foundation/foundation/components/_icon-bar.scss
  themes/helm/static/src/sass/foundation/foundation/components/_inline-lists.scss
  themes/helm/static/src/sass/foundation/foundation/components/_joyride.scss
  themes/helm/static/src/sass/foundation/foundation/components/_keystrokes.scss
  themes/helm/static/src/sass/foundation/foundation/components/_labels.scss
  themes/helm/static/src/sass/foundation/foundation/components/_magellan.scss
  themes/helm/static/src/sass/foundation/foundation/components/_offcanvas.scss
  themes/helm/static/src/sass/foundation/foundation/components/_orbit.scss
  themes/helm/static/src/sass/foundation/foundation/components/_pagination.scss
  themes/helm/static/src/sass/foundation/foundation/components/_panels.scss
  themes/helm/static/src/sass/foundation/foundation/components/_pricing-tables.scss
  themes/helm/static/src/sass/foundation/foundation/components/_progress-bars.scss
  themes/helm/static/src/sass/foundation/foundation/components/_range-slider.scss
  themes/helm/static/src/sass/foundation/foundation/components/_reveal.scss
  themes/helm/static/src/sass/foundation/foundation/components/_side-nav.scss
  themes/helm/static/src/sass/foundation/foundation/components/_split-buttons.scss
  themes/helm/static/src/sass/foundation/foundation/components/_sub-nav.scss
  themes/helm/static/src/sass/foundation/foundation/components/_switches.scss
  themes/helm/static/src/sass/foundation/foundation/components/_tables.scss
  themes/helm/static/src/sass/foundation/foundation/components/_tabs.scss
  themes/helm/static/src/sass/foundation/foundation/components/_thumbs.scss
  themes/helm/static/src/sass/foundation/foundation/components/_tooltips.scss
  themes/helm/static/src/sass/foundation/foundation/components/_top-bar.scss
  themes/helm/static/src/sass/foundation/foundation/components/_type.scss
  themes/helm/static/src/sass/foundation/foundation/components/_visibility.scss
  themes/helm/static/src/sass/foundation/normalize.scss
  themes/helm/static/src/sass/styles.scss
  yarn.lock
Labels: size/XXL

#235 #233 (docs): Improve layout for code line length
  themes/helm/static/src/sass/docs-content.scss
Labels: size/S

#239 Add editorconfig file
  .editorconfig
Labels: size/S

#244 [230] ensure gulp does not wipe away content/docs/
  gulpfile.js
Labels: bug, size/XS

#243 [#240] make search tool clickable again
  themes/helm/static/src/sass/docs-sidebar.scss
Labels: size/XS

#242 [#139] change overflow value to resolve firefox keyboard scroll issue
  themes/helm/static/src/sass/docs-layout.scss
Labels: bug, size/XS

#246 [#230] fix the grid layout for v3 docs
  layouts/docs/list.html
  layouts/docs/single.html
Labels: awaiting review, bug, size/S, v3

#251 Update related.md
  content/docs/community/related.md
Labels: size/XS

#252 Updated the release docs to bring in latest changes
  content/docs/community/release_checklist.md
Labels: size/L, v3
