Repository helm/helm-www, pull requests merged in 2019-12, with the labels that each got.

#402 [docs] reinstate the site search for v3 docs
  themes/helm/assets/js/app.js
  themes/helm/assets/sass/docs-sidebar.scss
  themes/helm/layouts/partials/sidebar.html
Labels: awaiting review, docs, size/S, v3

#396 Fix typo in rbac guide
  content/docs/topics/rbac.md
Labels: size/XS

#391 Fix some syntax inconsistency
  content/docs/topics/v2_v3_migration.md
Labels: size/XS

#404 update the docs quicklinks with some common question topics
  config.toml
Labels: awaiting review, docs, size/S

#419 Multiple service accounts example correction
  content/docs/topics/chart_best_practices/rbac.md
Labels: docs, size/XS

#395 Update hook and test documentation for Helm 3
  content/docs/faq.md
  content/docs/topics/chart_tests.md
  content/docs/topics/charts_hooks.md
  content/docs/topics/v2_v3_migration.md
Labels: docs, size/L, v3

#406 charts.md: Fix typos, whitespace, markdownlint
  content/docs/topics/charts.md
Labels: size/M

#426 Fix typo in charts_hooks.md
  content/docs/topics/charts_hooks.md
Labels: size/XS

#428 Fix Issue #418
  themes/helm/assets/sass/helm-home.scss
Labels: size/XS

#425 [#424] remove duplicate javascript
  themes/helm/assets/js/app.js
Labels: awaiting review, bug, docs, size/S

#435 Add Martin Hickey as core maintainer
  OWNERS
Labels: size/XS

#427 Fixing the command to get the log messages
  content/docs/community/release_checklist.md
Labels: size/XS

#430 [docs] Fix chart repository doc image paths
  content/docs/topics/chart_repository.md
Labels: in progress, size/S

#444 Fix description for `app.kubernetes.io/managed-by` label
  content/docs/topics/chart_best_practices/labels.md
Labels: size/XS

#442 add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: awaiting review, size/L

#445 Add Codecademy logo to footer
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/codecademy.png
Labels: size/XS

#446 Changed download file extension to .tar.gz to match the download files
  content/docs/intro/install.md
Labels: size/XS
