Repository helm/helm-www, pull requests merged in 2019-01, with the labels that each got.

#168 Broken URL Patching
  docs.helm.sh/gulpfile.js
Labels: awaiting review, bug, size/M

#169 update packages for security vulnerabilities
  docs.helm.sh/package-lock.json
  docs.helm.sh/package.json
  helm.sh/Gemfile.lock
  helm.sh/package-lock.json
  helm.sh/package.json
Labels: awaiting review, size/XXL

#171 Adding blog posts announcing 2 security releases
  helm.sh/_posts/2019-01-14-chartmuseum-security-notice.md
  helm.sh/_posts/2019-01-14-helm-security-notice.md
Labels: size/M

#172 fix(ci): bump base image for node
  brigade.js
Labels: size/XS

#173 Add missing hyphen
  helm.sh/_posts/2019-01-14-helm-security-notice.md
Labels: size/XS

#174 Use correct hyphen
  helm.sh/_posts/2019-01-14-helm-security-notice.md
Labels: size/XS

#175 Typo fix - doc site name
  docs.helm.sh/themes/helmdocs/layouts/index.html
Labels: size/XS
