Repository helm/helm-www, pull requests merged in 2019-02, with the labels that each got.

#177 Adding CVE ids to blog posts
  helm.sh/_posts/2019-01-14-chartmuseum-security-notice.md
  helm.sh/_posts/2019-01-14-helm-security-notice.md
Labels: size/XS

#178 Resolve hugo build error
  docs.helm.sh/config.toml
Labels: bug, size/XS

#179 Typo in blog
  helm.sh/_posts/2019-01-14-chartmuseum-security-notice.md
Labels: size/XS

#180 fix submenu links for new structure
  themes/helm/layouts/partials/offcanvas.html
Labels: bug, docs, size/XS

#182 [#181] update the url replace task for helm command docs (helm > helm)
  gulpfile.js
Labels: bug, docs, size/XS

#183 Fixing blog URLs
  README.md
  content/blog/2018-06-01-cncf.md
  content/blog/2018-07-23-bring-helm-home.md
  content/blog/2018-07-24-helm-emeritus-rimus.md
  content/blog/2018-08-27-helm-switch-dco.md
  content/blog/2018-09-07-new-gov-and-elections.md
  content/blog/2018-09-25-chart-testing-intro.md
  content/blog/2018-10-04-helm-org-maintainers.md
  content/blog/2018-12-11-helm-hub.md
  content/blog/2019-01-14-chartmuseum-security-notice.md
  content/blog/2019-01-14-helm-security-notice.md
Labels: size/M

#184 Fixing broken image link
  README.md
  content/blog/2018-12-11-helm-hub.md
Labels: size/XS
