Repository helm/helm-www, pull requests merged in 2019-08, with the labels that each got.

#254 Updating zoom link for weekly call
  themes/helm/layouts/index.html
Labels: size/XS

#253 docs(faq): 3-way merge patch, XDG, storage driver
  content/docs/faq.md
Labels: docs, size/L

#255 docs(faq): mark OCI as experimental, add note about apiVersion bump
  content/docs/faq.md
Labels: awaiting review, docs, size/S, v3

#257 Pre-beta registry doc updates
  content/docs/topics/registries.md
Labels: size/L

#258 registries typo
  content/docs/topics/registries.md
Labels: size/XS

#261 Restructure templating system
  config.toml
  netlify.toml
  themes/helm/layouts/404.html
  themes/helm/layouts/404/index.html
  themes/helm/layouts/_default/baseof.html
  themes/helm/layouts/_default/list.html
  themes/helm/layouts/_default/section.html
  themes/helm/layouts/_default/single.html
  themes/helm/layouts/blog/list.html
  themes/helm/layouts/blog/single.html
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/docs/single.html
  themes/helm/layouts/index.html
  themes/helm/layouts/partials/css.html
  themes/helm/layouts/partials/footer-blog.html
  themes/helm/layouts/partials/footer-home.html
  themes/helm/layouts/partials/footer.html
  themes/helm/layouts/partials/google-analytics.html
  themes/helm/layouts/partials/header.html
  themes/helm/layouts/partials/meta.html
  themes/helm/layouts/post/single.html
  themes/helm/layouts/section/single.html
Labels: size/XL

#272 (docs): add version dropdown to v3.helm.sh
  themes/helm/assets/sass/docs-responsive.scss
  themes/helm/assets/sass/docs-topbar.scss
  themes/helm/assets/sass/helm-home.scss
  themes/helm/assets/sass/styles.scss
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/index.html
  themes/helm/layouts/partials/banner.html
  themes/helm/layouts/partials/nav.html
Labels: awaiting review, size/L, v3

#273 Set versions via site configuration
  config.toml
  themes/helm/layouts/partials/nav.html
Labels: size/M
