Repository helm/helm-www, pull requests merged in 2019-05, with the labels that each got.

#211 Create 2019-05-02-helm-3-preview-pt4.md
  content/blog/2019-05-02-helm-3-preview-pt4.md
Labels: size/M

#212 Added in link to next blog post series
  content/blog/2019-04-29-helm-3-preview-pt3.md
Labels: size/XS

#213 Create 2019-05-06-helm-3-preview-pt5.md
  content/blog/2019-05-06-helm-3-preview-pt5.md
Labels: size/M

#214 Added in link to next blog post series
  content/blog/2019-05-02-helm-3-preview-pt4.md
Labels: size/XS

#216 Create 2019-05-09-helm-3-preview-pt6.md
  content/blog/2019-05-09-helm-3-preview-pt6.md
Labels: size/S

#215 fix homepage positioning for mobile layouts
  themes/helm/static/src/sass/docs-home.scss
  themes/helm/static/src/sass/docs-responsive.scss
Labels: awaiting review, bug, size/XS

#219 Added in link to next blog post series
  content/blog/2019-05-09-helm-3-preview-pt6.md
Labels: size/XS

#218 Create 2019-05-13-helm-3-preview-pt7.md
  content/blog/2019-05-13-helm-3-preview-pt7.md
Labels: size/S

#221 [v3] add a sticky banner for helm 2 and helm info
  themes/helm/layouts/blog/list.html
  themes/helm/layouts/blog/single.html
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/index.html
  themes/helm/layouts/partials/banner.html
  themes/helm/layouts/partials/topbar.html
  themes/helm/static/src/sass/docs-home.scss
  themes/helm/static/src/sass/docs-responsive.scss
  themes/helm/static/src/sass/docs-sidebar.scss
  themes/helm/static/src/sass/docs-topbar.scss
  themes/helm/static/src/sass/helm-home.scss
Labels: size/L, v3

#222 fix(go-import): fix go path on meta tags
  themes/helm/layouts/code/single.html
Labels: size/XS
