Repository helm/helm-www, pull requests merged in 2019-06, with the labels that each got.

#223 update packages
  package.json
  yarn.lock
Labels: security, size/XL

#224 bump packages
  package.json
  yarn.lock
Labels: size/M

#225 [HOLD] add blog post on get.helm.sh
  content/blog/2019-06-10-get-helm-sh.md
Labels: size/M

#226 Helm 3: add registry docs to sidebar
  config.toml
  gulpfile.js
Labels: size/XS
