Repository helm/helm-www, pull requests merged in 2019-04, with the labels that each got.

#197 feat(go-import): support branch selection for go vanity urls
  content/code/helm.md
  themes/helm/layouts/code/single.html
Labels: size/S

#201 Create helm-summit-eu-2019.md
  content/blog/helm-summit-eu-2019.md
Labels: size/S

#202 Renamed file name to include date
  content/blog/2019-04-18-helm-summit-eu-2019.md
Labels: size/XS

#203 Create 2019-04-22-helm-3-preview-pt1.md
  content/blog/2019-04-22-helm-3-preview-pt1.md
Labels: size/M

#205 Create 2019-04-25-helm3-preview-pt2.md
  content/blog/2019-04-25-helm-3-preview-pt2.md
Labels: size/S

#204 Added in link to next blog post series
  content/blog/2019-04-22-helm-3-preview-pt1.md
Labels: size/XS

#207 Added in link to next blog post series
  content/blog/2019-04-25-helm-3-preview-pt2.md
Labels: size/XS

#208 Create 2019-04-29-helm3-preview-pt3.md
  content/blog/2019-04-29-helm-3-preview-pt3.md
Labels: size/M

#209 Fix "next" link
  content/blog/2019-04-25-helm-3-preview-pt2.md
Labels: size/XS

#210 [187] add rss feed to blog posts
  themes/helm/layouts/blog/list.html
  themes/helm/layouts/blog/single.html
  themes/helm/layouts/partials/header.html
  themes/helm/static/src/sass/helm-blog.scss
Labels: blog, size/M
