Repository helm/helm-www, pull requests merged in 2019-03, with the labels that each got.

#186 feat(go-imports): configure vanity go import path
  config.toml
  content/code/helm.md
  themes/helm/layouts/code/single.html
Labels: size/S

#191 [#190] update build task to correct best practices toc
  gulpfile.js
Labels: awaiting review, docs, size/XS

#193 remove unused gulp packages
  gulpfile.js
  package.json
  yarn.lock
Labels: awaiting review, size/XXL

#189 rework the css boat animation
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/index.html
  themes/helm/static/src/img/boat.gif
  themes/helm/static/src/sass/docs-home.scss
  themes/helm/static/src/sass/docs-responsive.scss
  themes/helm/static/src/sass/helm-animation.scss
  themes/helm/static/src/sass/helm-blog.scss
  themes/helm/static/src/sass/helm-home.scss
  themes/helm/static/src/sass/styles.scss
Labels: awaiting review, enhancement, size/L

#194 Feat/add docsearch
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/partials/header.html
  themes/helm/layouts/partials/js.html
  themes/helm/layouts/partials/sidebar.html
  themes/helm/static/src/sass/docs-sidebar.scss
Labels: size/S

#195 Fixing broken links on blog
  content/blog/2018-06-01-cncf.md
  content/blog/2018-07-24-helm-emeritus-rimus.md
Labels: size/XS
