Repository helm/helm-www, pull requests merged in 2019-11, with the labels that each got.

#331 docs(theme): fix the v3 docs landing pages
  themes/helm/assets/sass/docs-content.scss
  themes/helm/assets/sass/docs-footer.scss
  themes/helm/assets/sass/docs-layout.scss
  themes/helm/assets/sass/docs-responsive.scss
  themes/helm/assets/sass/docs-sidebar.scss
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/docs/single.html
  themes/helm/layouts/partials/offcanvas.html
Labels: size/L, v3

#332 Adding post on results of Helm security audit
  content/blog/2019-11-04-helm-security-audit-results.md
Labels: size/M

#333 Updates plugin documentation with current env vars
  content/docs/topics/plugins.md
Labels: size/M

#335 Fix spelling oopz
  content/blog/2019-11-04-helm-security-audit-results.md
Labels: size/XS

#334 Updates CRD documentation with the latest instructions for v3
  content/docs/topics/chart_best_practices/custom_resource_definitions.md
Labels: size/M

#330 Adding back .helmignore documentation
  config.toml
  gulpfile.js
Labels: size/S

#337 ref(docs): move some documents to the topic guides
  content/docs/topics/kubernetes_distros.md
  content/docs/topics/rbac.md
  content/docs/topics/v2_v3_migration.md
Labels: size/S

#339 fix(docs): fix hyperlink lookups
  content/docs/howto/chart_repository_sync_example.md
  content/docs/intro/quickstart.md
  content/docs/intro/using_helm.md
  content/docs/topics/chart_repository.md
  content/docs/topics/chart_template_guide/builtin_objects.md
  content/docs/topics/chart_template_guide/subcharts_and_globals.md
  content/docs/topics/charts.md
  content/docs/topics/plugins.md
  content/docs/topics/registries.md
Labels: size/M

#338 fix(docs): remove section "Understanding your Security Context"
  content/docs/intro/quickstart.md
Labels: size/S

#344 add idea folder to .gitignore
  .gitignore
Labels: size/XS

#347 Adding blog post on community management
  content/blog/2019-11-11-community-management.md
Labels: size/S

#350 change references to v2 (older version) and v3 (stable)
  config.toml
  themes/helm/layouts/partials/banner.html
Labels: size/S, v3

#345 Update v3 Readme
  README.md
  themes/helm/layouts/partials/sidebar.html
Labels: size/L, v3

#348 Update v2 Readme
  README.md
Labels: size/S, v3

#352 chore(code): parity between code URLs
  content/code/chartmuseum.md
  content/code/helm-v2.md
  content/code/helm-v3.md
Labels: size/S, v3

#351 Blog: parity between versions
  content/blog/2019-08-27-helm-v3-beta.md
  content/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
  content/blog/2019-10-22-helm-2150-released.md
  content/blog/2019-10-30-helm-symlink-security-notice.md
  content/blog/2019-11-04-helm-security-audit-results.md
  content/blog/2019-11-11-community-management.md
  content/blog/images/helm-2to3.png
Labels: size/XL, v3

#341 fix(index): fix docs link
  themes/helm/layouts/index.html
Labels: size/S

#353 remove instructions for 'make docs', which is gone
  content/docs/community/developers.md
Labels: size/S

#354 remove docker-build instructions for tiller
  content/docs/community/developers.md
Labels: size/S

#356 fix(docs): use HTTPS everywhere
  content/blog/2018-12-11-helm-hub.md
  content/docs/community/developers.md
  content/docs/community/history.md
  content/docs/community/related.md
  content/docs/community/release_checklist.md
  content/docs/intro/getting_started.md
  content/docs/intro/using_helm.md
  content/docs/topics/chart_best_practices/conventions.md
  content/docs/topics/chart_template_guide/control_structures.md
  content/docs/topics/chart_template_guide/yaml_techniques.md
  content/docs/topics/charts.md
  content/docs/topics/plugins.md
  content/docs/topics/provenance.md
Labels: size/M

#359 Update the Helm history and remove unnecessary content
  content/docs/community/history.md
Labels: size/M

#358 docs: update the provenance documentation for Helm 3
  content/docs/topics/provenance.md
Labels: size/M

#357 docs: update documentation on building Helm
  content/docs/community/developers.md
Labels: size/S

#361 fix URLs for adding new related links
  content/docs/community/related.md
Labels: size/XS

#360 add hugo alias redirects for applicable v2 urls
  content/docs/community/developers.md
  content/docs/community/history.md
  content/docs/community/related.md
  content/docs/howto/chart_repository_sync_example.md
  content/docs/howto/charts_tips_and_tricks.md
  content/docs/intro/_index.md
  content/docs/intro/getting_started.md
  content/docs/intro/install.md
  content/docs/intro/quickstart.md
  content/docs/topics/architecture.md
  content/docs/topics/chart_best_practices/_index.md
  content/docs/topics/chart_repository.md
  content/docs/topics/chart_template_guide/_index.md
  content/docs/topics/chart_tests.md
  content/docs/topics/charts.md
  content/docs/topics/charts_hooks.md
  content/docs/topics/kubernetes_distros.md
  content/docs/topics/plugins.md
  content/docs/topics/provenance.md
  content/docs/topics/rbac.md
  content/docs/topics/registries.md
Labels: size/S, v3

#349 fix(templates): fix "incorrect" example
  content/docs/topics/chart_best_practices/templates.md
Labels: size/XS

#362 fix: update formatting and content of tips and tricks
  content/docs/howto/charts_tips_and_tricks.md
Labels: size/M

#363 fix(install): update links to get-helm-3 script
  content/docs/community/release_checklist.md
  content/docs/faq.md
  content/docs/intro/install.md
Labels: size/S

#343 docs: add apiVersion v1 and v2 description to to Chart.yaml docs.
  content/docs/topics/charts.md
Labels: size/S

#365 fix: update best practices
  content/docs/topics/chart_best_practices/conventions.md
Labels: size/XS

#366 fix: fixed formatting in templates.md
  content/docs/topics/chart_best_practices/templates.md
Labels: size/XS

#367 fix: fixed formatting of YAML samples
  content/docs/topics/chart_best_practices/values.md
Labels: size/S

#368 fix: minor fixes to the accessing-files.md document
  content/docs/topics/chart_template_guide/accessing_files.md
Labels: size/S

#370 fix: update debugging doc for helm 3
  content/docs/topics/chart_template_guide/debugging.md
Labels: size/S

#371 fix: fixed formatting in functions and pipelines docs
  content/docs/topics/chart_template_guide/functions_and_pipelines.md
Labels: size/XS

#364 Update the using-helm doc to v3
  content/docs/intro/using_helm.md
Labels: size/L

#369 fix: Updated builtin objects for Helm 3
  content/docs/topics/chart_template_guide/builtin_objects.md
Labels: size/S

#372 update hooks for Helm 3
  content/docs/topics/charts_hooks.md
Labels: size/S

#373 fix: fix misc formatting issues
  content/docs/topics/charts.md
  content/docs/topics/kubernetes_distros.md
  content/docs/topics/plugins.md
Labels: size/S

#375 [v3] fix /blog redirect loop
  netlify.toml
Labels: bug, size/M

#376 [v2] site versioning adjustments
  netlify.toml
Labels: docs, size/M

#378 feat(blog): Helm 3.0.0 has been released!
  content/blog/2019-11-13-helm-3-released.md
Labels: size/L

#380 Adding back go get metadata template
  themes/helm/layouts/code/single.html
Labels: size/S

#384 Added that CNCF funded sec audit to the blog post
  content/blog/2019-11-04-helm-security-audit-results.md
Labels: size/XS

#388 Update migration 2 to 3 post with latest plugin changes
  content/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
Labels: size/L

#387 Fix uninstall default behavior
  content/docs/intro/quickstart.md
Labels: size/XS

#386 Fix helm inspect format
  content/docs/intro/quickstart.md
Labels: size/XS

#389 Replace helm inspect with helm inspect
  content/docs/intro/using_helm.md
Labels: size/XS

#390 Use the v3 tarball by default
  content/docs/intro/install.md
Labels: size/XS

#392 Adding post on kubecon + cloudnativecon NA 2019
  content/blog/2019-11-11-community-management copy.md
Labels: size/S

#393 fixing url to blog post
  content/blog/2019-11-15-helm-at-cloudnativecon.md
Labels: size/XS

#399 Remove repeated word 'to' in v2_v3_migration.md
  content/docs/topics/v2_v3_migration.md
Labels: size/XS

#400 Update homebrew formula name
  content/docs/intro/install.md
Labels: size/XS

#398 Fix duplicate in quick links
  config.toml
Labels: size/XS

#403 [v2] switch the docs search to helm_v2 index
  themes/helm/assets/js/app.js
  themes/helm/layouts/partials/js.html
Labels: docs, size/XS

#407 Add weights to topics with multiple pages
  content/docs/topics/chart_best_practices/conventions.md
  content/docs/topics/chart_best_practices/custom_resource_definitions.md
  content/docs/topics/chart_best_practices/dependencies.md
  content/docs/topics/chart_best_practices/labels.md
  content/docs/topics/chart_best_practices/pods.md
  content/docs/topics/chart_best_practices/rbac.md
  content/docs/topics/chart_best_practices/templates.md
  content/docs/topics/chart_best_practices/values.md
  content/docs/topics/chart_template_guide/accessing_files.md
  content/docs/topics/chart_template_guide/builtin_objects.md
  content/docs/topics/chart_template_guide/control_structures.md
  content/docs/topics/chart_template_guide/data_types.md
  content/docs/topics/chart_template_guide/debugging.md
  content/docs/topics/chart_template_guide/functions_and_pipelines.md
  content/docs/topics/chart_template_guide/named_templates.md
  content/docs/topics/chart_template_guide/notes_files.md
  content/docs/topics/chart_template_guide/subcharts_and_globals.md
  content/docs/topics/chart_template_guide/values_files.md
  content/docs/topics/chart_template_guide/variables.md
  content/docs/topics/chart_template_guide/yaml_techniques.md
Labels: size/S

#409 v2_v3_migration.md: explicitly mention the Helm version in note
  content/docs/topics/v2_v3_migration.md
Labels: size/XS

#410 fix some wrong commands
  content/docs/intro/using_helm.md
Labels: size/XS

#412 remove helm serve command from charts docs
  content/docs/topics/charts.md
Labels: size/XS
