Repository helm/helm-www, pull requests merged in 2020-12, with the labels that each got.

#944 [ko] translate helm test command in korean
  content/ko/docs/helm/helm_test.md
Labels: size/M

#956 Update README to use new --generate-headers
  README.md
Labels: size/XS

#976 [ko] Translate chart_repository_sync_example in Korean
  content/ko/docs/howto/chart_repository_sync_example.md
Labels: size/M

#978 [zh] Update helm title for Chinese docs
  content/zh/docs/helm/helm.md
  content/zh/docs/helm/helm_delete.md
  content/zh/docs/helm/helm_get.md
  content/zh/docs/helm/helm_install.md
  content/zh/docs/helm/helm_lint.md
  content/zh/docs/helm/helm_package.md
  content/zh/docs/helm/helm_plugin.md
  content/zh/docs/helm/helm_plugin_install.md
  content/zh/docs/helm/helm_plugin_list.md
  content/zh/docs/helm/helm_plugin_uninstall.md
  content/zh/docs/helm/helm_plugin_update.md
  content/zh/docs/helm/helm_pull.md
  content/zh/docs/helm/helm_repo.md
  content/zh/docs/helm/helm_repo_add.md
  content/zh/docs/helm/helm_repo_index.md
  content/zh/docs/helm/helm_repo_list.md
  content/zh/docs/helm/helm_repo_remove.md
  content/zh/docs/helm/helm_repo_update.md
  content/zh/docs/helm/helm_rollback.md
  content/zh/docs/helm/helm_search.md
  content/zh/docs/helm/helm_search_hub.md
  content/zh/docs/helm/helm_show.md
  content/zh/docs/helm/helm_show_all.md
  content/zh/docs/helm/helm_show_chart.md
  content/zh/docs/helm/helm_show_readme.md
  content/zh/docs/helm/helm_show_values.md
  content/zh/docs/helm/helm_template.md
  content/zh/docs/helm/helm_test.md
  content/zh/docs/intro/install.md
  content/zh/docs/topics/registries.md
Labels: size/M

#939 [ko] translate blog(helm-turns-five) into Korean
  content/ko/blog/2020-10-19-helm-turns-five.md
  content/ko/blog/images/happy-5th.png
  content/ko/blog/images/octocat.png
Labels: size/M

#987 Update charts.md
  content/en/docs/topics/charts.md
Labels: size/XS

#937 [ko] translate blog(helm-hub-moving-artifact-hub) into Korean
  content/ko/blog/2020-10-07-helm-hub-moving-artifact-hub.md
Labels: size/M

#935 [ko] translate command/helm-upgrade into Korean
  content/ko/docs/helm/helm_upgrade.md
Labels: size/L

#972 [ko] Translate helm command : helm history in Korean
  content/ko/docs/helm/helm_history.md
Labels: size/M

#980 [ko] translate helm plugin command into Korean
  content/ko/docs/helm/helm_plugin.md
  content/ko/docs/helm/helm_plugin_install.md
  content/ko/docs/helm/helm_plugin_list.md
  content/ko/docs/helm/helm_plugin_uninstall.md
  content/ko/docs/helm/helm_plugin_update.md
Labels: size/L

#975 Update ko doc about "PR : Clarifications in the v2 to v3 migration"
  content/ko/docs/topics/v2_v3_migration.md
Labels: size/XS

#988 [zh] Update Chinese docs for best practices
  content/zh/docs/chart_best_practices/conventions.md
  content/zh/docs/chart_best_practices/custom_resource_definitions.md
  content/zh/docs/chart_best_practices/dependencies.md
  content/zh/docs/chart_best_practices/labels.md
  content/zh/docs/chart_best_practices/pods.md
  content/zh/docs/chart_best_practices/rbac.md
  content/zh/docs/chart_best_practices/templates.md
  content/zh/docs/chart_best_practices/values.md
  content/zh/docs/chart_template_guide/values_files.md
  content/zh/docs/faq/_index.md
  content/zh/docs/intro/using_helm.md
  content/zh/docs/topics/charts.md
Labels: size/XL

#996 Updating for v3.4.2
  config.toml
Labels: size/XS

#933 [ko] translate topics/provenance into Korean
  content/ko/docs/topics/provenance.md
Labels: size/L, translation

#998 fix typo
  content/zh/docs/intro/using_helm.md
Labels: size/XS
