Repository helm/helm-www, pull requests merged in 2020-07, with the labels that each got.

#736 Removing aliases to ko docs
  content/ko/docs/chart_best_practices/conventions.md
  content/ko/docs/chart_best_practices/custom_resource_definitions.md
  content/ko/docs/chart_best_practices/dependencies.md
  content/ko/docs/chart_best_practices/labels.md
  content/ko/docs/chart_best_practices/pods.md
  content/ko/docs/chart_best_practices/rbac.md
  content/ko/docs/chart_best_practices/templates.md
  content/ko/docs/chart_best_practices/values.md
  content/ko/docs/chart_template_guide/getting_started.md
  content/ko/docs/community/history.md
  content/ko/docs/intro/install.md
  content/ko/docs/intro/quickstart.md
  content/ko/docs/topics/architecture.md
Labels: awaiting review

#538 Add permissions management doc for SQL storage backend
  content/en/docs/topics/permissions_sql_storage_backend.md
Labels: awaiting review, enhancement, size/M

#739 Clarify valid chart naming scheme
  content/en/docs/chart_best_practices/conventions.md
Labels: size/XS

#740 Explaining what $ is
  content/en/docs/chart_template_guide/control_structures.md
Labels: size/S

#742 rephrasing uses of "Kubernetes Helm" in docs
  content/en/docs/topics/architecture.md
  content/en/docs/topics/charts.md
Labels: size/XS

#730 refine info on install order of hooks.
  content/en/docs/topics/charts_hooks.md
Labels: size/XS

#743 feat(docs): introduce markdownlint.json
  .markdownlint.json
  content/en/docs/_index.md
  content/en/docs/chart_best_practices/conventions.md
  content/en/docs/chart_best_practices/custom_resource_definitions.md
  content/en/docs/chart_best_practices/dependencies.md
  content/en/docs/chart_best_practices/rbac.md
  content/en/docs/chart_template_guide/accessing_files.md
  content/en/docs/chart_template_guide/builtin_objects.md
  content/en/docs/chart_template_guide/control_structures.md
  content/en/docs/chart_template_guide/debugging.md
  content/en/docs/chart_template_guide/function_list.md
  content/en/docs/chart_template_guide/functions_and_pipelines.md
  content/en/docs/chart_template_guide/getting_started.md
  content/en/docs/chart_template_guide/helm_ignore_file.md
  content/en/docs/chart_template_guide/named_templates.md
  content/en/docs/chart_template_guide/notes_files.md
  content/en/docs/chart_template_guide/subcharts_and_globals.md
  content/en/docs/chart_template_guide/values_files.md
  content/en/docs/chart_template_guide/wrapping_up.md
  content/en/docs/community/developers.md
  content/en/docs/community/history.md
  content/en/docs/community/localization.md
  content/en/docs/community/related.md
  content/en/docs/community/release_checklist.md
  content/en/docs/faq/_index.md
  content/en/docs/howto/chart_repository_sync_example.md
  content/en/docs/howto/charts_tips_and_tricks.md
  content/en/docs/intro/install.md
  content/en/docs/intro/quickstart.md
  content/en/docs/intro/using_helm.md
  content/en/docs/topics/advanced.md
  content/en/docs/topics/chart_repository.md
  content/en/docs/topics/chart_tests.md
  content/en/docs/topics/charts.md
  content/en/docs/topics/charts_hooks.md
  content/en/docs/topics/kubernetes_apis.md
  content/en/docs/topics/kubernetes_distros.md
  content/en/docs/topics/library_charts.md
  content/en/docs/topics/permissions_sql_storage_backend.md
  content/en/docs/topics/plugins.md
  content/en/docs/topics/provenance.md
  content/en/docs/topics/registries.md
  content/en/docs/topics/v2_v3_migration.md
  content/en/docs/topics/version_skew.md
Labels: size/XXL

#558 Add the SQL storage backend doc
  content/en/docs/topics/advanced.md
Labels: size/M

#746 Revert unmerged OCI dependency changes
  content/en/docs/chart_best_practices/dependencies.md
  content/en/docs/topics/registries.md
Labels: size/S

#747 Add missing dollar sign
  content/en/docs/intro/quickstart.md
Labels: size/XS

#725 [ko] chart_best_practices/rbac.md
  content/ko/docs/chart_best_practices/rbac.md
Labels: size/M, translation

#750 Minor formatting fix
  content/en/docs/chart_template_guide/builtin_objects.md
  content/en/docs/chart_template_guide/getting_started.md
Labels: size/XS

#748 Add Amazon EKS to helm docs topics kubernetes_distros
  content/en/docs/topics/kubernetes_distros.md
Labels: size/XS

#751 Change template directive names to complete names to align with others
  content/en/docs/chart_template_guide/builtin_objects.md
Labels: bug, size/XS

#752 Fix caret ranges description
  content/en/docs/topics/charts.md
Labels: size/XS

#749 Updating release checklist
  content/en/docs/community/release_checklist.md
  content/en/docs/images/nothing.png
Labels: size/L

#754 Fix a bad Markdown link to keybase.io
  content/en/docs/topics/provenance.md
Labels: size/XS

#719 Add Japanese Translation.
  config.toml
  content/ja/docs/_index.md
  content/ja/docs/chart_best_practices/_index.md
  content/ja/docs/chart_template_guide/_index.md
  content/ja/docs/chart_template_guide/data_types.md
  content/ja/docs/community/_index.md
  content/ja/docs/helm/_index.md
  content/ja/docs/howto/_index.md
  content/ja/docs/images/create-a-bucket.png
  content/ja/docs/images/create-a-gh-page-button.png
  content/ja/docs/images/edit-permissions.png
  content/ja/docs/images/make-bucket-public.png
  content/ja/docs/images/nothing.png
  content/ja/docs/images/set-a-gh-page.png
  content/ja/docs/intro/_index.md
  content/ja/docs/intro/install.md
  content/ja/docs/intro/quickstart.md
  content/ja/docs/intro/using_helm.md
  content/ja/docs/logos/helm-blue-vector.svg
  content/ja/docs/logos/helm-white-vector.svg
  content/ja/docs/logos/helm.svg
  content/ja/docs/logos/helm_logo_transparent.png
  content/ja/docs/topics/_index.md
  content/ja/docs/topics/advanced.md
  content/ja/docs/topics/architecture.md
  content/ja/docs/topics/chart_tests.md
  i18n/ja.toml
Labels: size/XXL, translation

#759 Specify full nested yaml property in imagePullPolicy of 'Pods and PodTemplates' best practices
  content/en/docs/chart_best_practices/pods.md
  content/ko/docs/chart_best_practices/pods.md
Labels: size/XS
