Repository helm/helm-www, pull requests merged in 2020-01, with the labels that each got.

#423 Fix argument `--maxHistory` -> `--history-max`
  content/docs/topics/v2_v3_migration.md
Labels: size/XS

#416 add link to hcunit plugin
  content/docs/community/related.md
Labels: awaiting review, size/XS

#440 Added docs for adding repos with --insecure-skip-tls-verify
  content/docs/topics/chart_repository.md
Labels: size/XS

#455 Adding the CVE id assigned to this vulnerability
  content/blog/2019-10-30-helm-symlink-security-notice.md
Labels: size/XS

#441 Add hint to add the stable repo
  content/docs/intro/install.md
Labels: awaiting review, size/XS

#448 Dependency repo alias explained
  content/docs/topics/charts.md
Labels: size/S

#453 remove "helm serve" content and refer to ChartMuseum instead
  content/docs/faq.md
  content/docs/topics/chart_repository.md
Labels: size/M

#454 Reduce common confusion around namespace changes in v3
  content/docs/faq.md
Labels: size/S

#436 [docs] Resort and reorganize the chart_template_guide
  content/docs/chart_template_guide/_index.md
  content/docs/chart_template_guide/accessing_files.md
  content/docs/chart_template_guide/builtin_objects.md
  content/docs/chart_template_guide/control_structures.md
  content/docs/chart_template_guide/data_types.md
  content/docs/chart_template_guide/debugging.md
  content/docs/chart_template_guide/functions_and_pipelines.md
  content/docs/chart_template_guide/getting_started.md
  content/docs/chart_template_guide/helm_ignore_file.md
  content/docs/chart_template_guide/named_templates.md
  content/docs/chart_template_guide/notes_files.md
  content/docs/chart_template_guide/subcharts_and_globals.md
  content/docs/chart_template_guide/values_files.md
  content/docs/chart_template_guide/variables.md
  content/docs/chart_template_guide/wrapping_up.md
  content/docs/chart_template_guide/yaml_techniques.md
Labels: awaiting review, docs, size/M

#457 Semver 2 link updated
  content/docs/topics/charts.md
Labels: size/XS

#420 Specify more flags to curl
  content/docs/intro/install.md
Labels: docs, size/XS

#456 suggest expanding OWNERS
  OWNERS
Labels: size/S

#449 Add plugins info for helm-s3 and helm-schema-gen
  content/docs/community/related.md
Labels: in progress, size/XS

#459 Update related.md
  content/docs/community/related.md
Labels: size/XS

#461 Fix link to Chart Template Guide
  content/docs/chart_template_guide/getting_started.md
Labels: size/XS

#458 docs: fixes getting started docs helm install command
  content/docs/chart_template_guide/getting_started.md
Labels: size/XS

#415 fix the capabilities object key name for kubernetes version
  content/docs/chart_template_guide/builtin_objects.md
Labels: awaiting review, bug, docs, size/XS, v3

#382 docs: add kubeVersion to Chart.yaml docs.
  content/docs/topics/charts.md
Labels: awaiting review, size/M

#464 Fixing the v2 docs link on the v2 site
  themes/helm/layouts/index.html
Labels: size/XS

#468 Broken URL for built-in objects in faq.md
  content/docs/faq.md
Labels: size/XS

#447 Getting started essential fixes
  content/docs/chart_template_guide/getting_started.md
Labels: awaiting review, size/M

#472 --generate-name is given to successfully install chart
  content/docs/intro/using_helm.md
Labels: size/XS

#470 fix(community): Port fixes from v2 release checklist
  content/docs/community/release_checklist.md
Labels: bug, docs, size/M

#462 Restoring docs on tpl template function
  content/docs/howto/charts_tips_and_tricks.md
Labels: size/M

#474 fix broken links on wrapping_up
  config.toml
  content/en/docs/chart_template_guide/wrapping_up.md
Labels: awaiting review, docs, size/XS

#431 document execute flag rename
  content/en/docs/topics/v2_v3_migration.md
Labels: size/XS

#476 Removed duplicate title
  content/en/docs/topics/chart_repository.md
Labels: size/XS

#477 remove numerical value for top-level objects
  content/en/docs/chart_template_guide/values_files.md
Labels: size/XS

#401 Reinstate the helm command docs
  README.md
  content/en/docs/community/_index.md
  content/en/docs/faq.md
  content/en/docs/glossary.md
  content/en/docs/helm/_index.md
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_delete.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_fetch.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_home.md
  content/en/docs/helm/helm_init.md
  content/en/docs/helm/helm_inspect.md
  content/en/docs/helm/helm_inspect_chart.md
  content/en/docs/helm/helm_inspect_values.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_remove.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_reset.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_serve.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
  themes/helm/assets/sass/docs-content.scss
  themes/helm/layouts/docs/helm/list.html
Labels: docs, size/XXL
