Repository helm/helm-www, pull requests merged in 2020-09, with the labels that each got.

#796 Add Chinese docs for faq and glossay
  content/zh/docs/faq/_index.md
  content/zh/docs/glossary/_index.md
Labels: size/XL

#798 Add chinese translation for quickstart page
  content/zh/docs/intro/install.md
  content/zh/docs/intro/quickstart.md
  content/zh/docs/intro/using_helm.md
Labels: size/L

#784 Clarify how define produces output
  content/en/docs/chart_template_guide/named_templates.md
Labels: size/XS

#788 Adding some clarifications
  content/en/docs/community/localization.md
Labels: size/S

#806 add FAQ about the mdns_debug file
  content/en/docs/faq/_index.md
Labels: size/S

#809 Fix spelling error
  content/ko/docs/helm/_index.md
Labels: size/XS

#801 Translate docs/chart_template_guide/debugging.md in Korean
  content/ko/docs/chart_template_guide/debugging.md
Labels: size/M

#812 The Fedora PackageDB project has been retired in favor of the pkgdb2 …
  content/en/docs/intro/using_helm.md
Labels: size/XS

#800 Translate docs/chart_template_guide/notes_files.md in Korean
  content/ko/docs/chart_template_guide/notes_files.md
Labels: size/S

#814 Use main branch for chartmuseum go mod
  content/code/chartmuseum.md
  content/en/code/chartmuseum.md
Labels: size/XS

#817 Adding clarification about APIVersion
  content/en/docs/faq/_index.md
Labels: size/XS

#808 Translate docs/community/related in Korean
  content/ko/docs/community/related.md
Labels: size/M

#804 Translate /docs/topics/kubernetes_distros in Korean
  content/ko/docs/topics/kubernetes_distros.md
Labels: question, size/M, translation

#823 Fix typo
  content/en/docs/topics/chart_repository.md
Labels: size/XS, translation

#828 Fix typo
  content/en/docs/intro/using_helm.md
Labels: size/XS

#811 Add Chinese docs and change newly path
  content/zh/docs/_index.md
  content/zh/docs/chart_template_guide/builtin_objects.md
  content/zh/docs/faq/_index.md
  content/zh/docs/topics/advanced.md
  content/zh/docs/topics/charts.md
  content/zh/docs/topics/registries.md
Labels: size/XXL, translation

#799 Translate docs/chart_template_guide/builtin_objects.md in Korean
  content/ko/docs/chart_template_guide/builtin_objects.md
  content/ko/docs/faq/_index.md
  content/ko/docs/howto/charts_tips_and_tricks.md
  content/ko/docs/topics/charts.md
  content/ko/docs/topics/library_charts.md
Labels: size/XXL, translation

#803 [ko] docs/chart_best_practices/templates.md
  content/ko/docs/chart_best_practices/templates.md
Labels: size/L, translation

#833 Fix typo
  content/en/docs/chart_template_guide/control_structures.md
Labels: size/XS

#824 Translate topics/chart_repository.md into Korean
  content/ko/docs/topics/chart_repository.md
Labels: size/L, translation

#835 version bump
  config.toml
Labels: size/XS

#836 yarn upgrade
  yarn.lock
Labels: size/L

#810 Translate docs/helm/helm_get in Korean
  content/ko/docs/helm/helm_get.md
  content/ko/docs/helm/helm_get_all.md
  content/ko/docs/helm/helm_get_hooks.md
  content/ko/docs/helm/helm_get_manifest.md
  content/ko/docs/helm/helm_get_notes.md
  content/ko/docs/helm/helm_get_values.md
Labels: in progress, size/L, translation

#807 Translate docs/helm/helm_env in Korean
  content/ko/docs/helm/helm_env.md
Labels: size/M, translation

#815 Translate helm command : helm status in Korean
  content/ko/docs/helm/helm_status.md
Labels: size/M, translation

#816 Translate helm command : helm package in Korean
  content/ko/docs/helm/helm_package.md
Labels: size/M, translation

#819 Translate helm command with helm show in Korean
  content/ko/docs/helm/helm_show.md
  content/ko/docs/helm/helm_show_all.md
  content/ko/docs/helm/helm_show_chart.md
  content/ko/docs/helm/helm_show_readme.md
  content/ko/docs/helm/helm_show_values.md
Labels: size/L, translation

#830 Translate helm command : uninstall in Korean
  content/ko/docs/helm/helm_uninstall.md
Labels: size/M, translation

#802 Translate /docs/helm/helm.md in Korean
  content/ko/docs/helm/helm.md
Labels: size/L, translation

#822 Translate chart_template_guide/getting_started.md into Korean
  content/ko/docs/chart_template_guide/getting_started.md
Labels: size/L, translation

#839 bump to v2.16.12/v3.3.3
  config.toml
Labels: size/XS

#840 Updating FAQ & docs for helm repo add
  content/en/docs/faq/_index.md
  content/en/docs/helm/helm_repo_add.md
Labels: size/S

#837 Translate command : helm create in Korean
  content/ko/docs/helm/helm_create.md
Labels: awaiting review, size/M, translation

#831 Translate helm/version_skew(Helm Version Support Policy) in Korean
  content/ko/docs/topics/version_skew.md
Labels: awaiting review, size/M, translation

#845 Translate docs/faq/ into Japanese
  content/ja/docs/faq/_index.md
Labels: size/XL

#864 Fixed docs on lookup function
  content/en/docs/chart_template_guide/functions_and_pipelines.md
Labels: size/XS

#827 Translate community/localization.md into Korean
  content/ko/docs/community/localization.md
Labels: size/L, translation

#848 Translate 'helm lint' command in Korean
  content/ko/docs/helm/helm_lint.md
Labels: awaiting review, size/M, translation

#838 Translate docs/topics/permissions_sql_storage_backend in Korean
  content/ko/docs/topics/permissions_sql_storage_backend.md
Labels: size/M, translation

#868 Bump version for 3.3.4
  config.toml
Labels: size/XS

#871 [en] missing parentheses
  content/en/docs/faq/_index.md
Labels: size/XS

#867 Add Kubernetes client logging to FAQ
  content/en/docs/faq/_index.md
Labels: size/S

#855 Translate /docs/chart_best_practices in Korean
  content/ko/docs/chart_best_practices/values.md
Labels: awaiting review, size/L, translation

#861 Translate 'helm version' command docs in Korean
  content/ko/docs/helm/helm_version.md
Labels: awaiting review, size/M, translation
