Repository helm/helm-www, pull requests merged in 2020-08, with the labels that each got.

#762 Update Debian repo signing key location
  content/en/docs/intro/install.md
Labels: size/XS

#760 show helm3 test hook example, not helm2
  content/en/docs/topics/chart_tests.md
Labels: size/XS

#767 Updating for CNCF graduation
  content/en/docs/community/history.md
Labels: size/XS

#768 updates for the 3.3.0 release
  config.toml
  content/en/docs/topics/version_skew.md
Labels: size/XS

#769 Adding blog post
  content/en/blog/2020-08-13-helm-v2-deprecation-timeline.md
Labels: size/M

#776 Add link to avionix
  content/en/docs/community/related.md
Labels: size/XS

#774 Removing aliases from ja translation
  content/ja/docs/chart_best_practices/_index.md
  content/ja/docs/chart_template_guide/_index.md
  content/ja/docs/intro/_index.md
  content/ja/docs/intro/install.md
  content/ja/docs/intro/quickstart.md
  content/ja/docs/topics/advanced.md
  content/ja/docs/topics/architecture.md
  content/ja/docs/topics/chart_tests.md
Labels: size/XS

#772 Using Helm doc: Link to info on Value Files and note missing next chapter
  content/en/docs/intro/using_helm.md
Labels: size/XS

#780 Remove XDG references from the plugin docs
  content/en/docs/topics/plugins.md
Labels: size/S

#766 Adding release notes details
  content/en/docs/community/release_checklist.md
Labels: size/S

#764 glossary translation
  content/ja/docs/glossary/_index.md
  content/ja/docs/topics/advanced.md
  i18n/ja.toml
Labels: size/L, translation

#777 Add Chinese doc first time.
  config.toml
  content/zh/docs/_index.md
  content/zh/docs/chart_best_practices/_index.md
  content/zh/docs/chart_template_guide/_index.md
  content/zh/docs/community/_index.md
  content/zh/docs/helm/_index.md
  content/zh/docs/howto/_index.md
  content/zh/docs/intro/_index.md
  content/zh/docs/topics/_index.md
  i18n/zh.toml
Labels: size/L, translation

#781 Clarify version skew
  content/en/docs/intro/quickstart.md
Labels: size/XS

#782 Clarify test success
  content/en/docs/topics/chart_tests.md
Labels: size/XS

#785 [zh] make urls absolute to fix builds
  content/zh/docs/_index.md
  i18n/zh.toml
Labels: awaiting review, size/S

#765 translate-history
  content/ja/docs/_index.md
  content/ja/docs/community/history.md
Labels: size/M, translation

#787 Removing incorrect aliases
  content/zh/docs/chart_best_practices/_index.md
  content/zh/docs/chart_template_guide/_index.md
  content/zh/docs/intro/_index.md
Labels: size/XS

#789 Update _index.md
  content/ko/docs/glossary/_index.md
Labels: size/XS

#791 Fix the style of docs in Chinese
  content/zh/docs/_index.md
  content/zh/docs/chart_best_practices/_index.md
  content/zh/docs/chart_template_guide/_index.md
  content/zh/docs/community/_index.md
  content/zh/docs/helm/_index.md
  content/zh/docs/intro/_index.md
  i18n/zh.toml
Labels: size/L

#792 Translate the rest of it.
  content/ja/docs/glossary/_index.md
Labels: size/M

#793 Translate ja advanced rest
  content/ja/docs/topics/advanced.md
Labels: size/L

#795 Update release checklist, 3.3.1 improvements
  config.toml
  content/en/docs/community/release_checklist.md
Labels: size/XS
