Repository helm/helm-www, pull requests merged in 2020-05, with the labels that each got.

#616 Updating the footer message to graduated
  i18n/en.toml
  i18n/zh.toml
  themes/helm/layouts/partials/cncf.html
Labels: size/XS

#559 feat(topics): Add doc on Kubernetes APIs
  content/en/docs/topics/kubernetes_apis.md
Labels: docs, enhancement, size/L

#621 add CNCF graduated status on main page
  i18n/en.toml
Labels: size/XS

#617 Clarify risks of using configmap backend
  content/en/docs/topics/advanced.md
Labels: size/S

#625 Review implemented
  i18n/ko.toml
Labels: size/XS

#629 Add include crd flag to options
  content/en/docs/helm/helm_template.md
Labels: bug, size/XS

#633 Fix invalid url to go sdk
  content/en/docs/topics/advanced.md
Labels: size/XS

#632 docs(helm): update docstrings to Helm 3.2.1
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_env.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_all.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_notes.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_uninstall.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_pull.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_search_hub.md
  content/en/docs/helm/helm_search_repo.md
  content/en/docs/helm/helm_show.md
  content/en/docs/helm/helm_show_all.md
  content/en/docs/helm/helm_show_chart.md
  content/en/docs/helm/helm_show_readme.md
  content/en/docs/helm/helm_show_values.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_uninstall.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
Labels: size/L

#634 Update doc version to release 3.2.1
  config.toml
Labels: size/XS

#623 add documentation about OCI dependencies
  content/en/docs/chart_best_practices/dependencies.md
  content/en/docs/topics/registries.md
Labels: size/S

#636 Kortrans0512
  i18n/ko.toml
Labels: size/S

#640 Fix examples how to use .Files.Glob
  content/en/docs/chart_template_guide/accessing_files.md
Labels: size/S

#642 FAQ Update for Create Namespace
  content/en/docs/faq/_index.md
Labels: size/XS

#626 [korean] docs/intro/using_helm.md
  content/ko/docs/intro/using_helm.md
Labels: size/L

#649 Specify behavior of lookup function during --dry-run
  content/en/docs/chart_template_guide/functions_and_pipelines.md
Labels: size/XS

#650 update helm versions in v2 website navbar
  config.toml
Labels: size/XS

#657 Add Montreal to contributor's logos
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/montreal.png
Labels: size/XS
