Repository helm/helm-www, pull requests merged in 2020-02, with the labels that each got.

#480 Corrected caps in description
  content/en/docs/topics/chart_best_practices/conventions.md
  content/en/docs/topics/kubernetes_distros.md
Labels: size/XS

#483 Fix --timeout flag
  content/en/docs/intro/using_helm.md
Labels: size/XS

#484 Remove obsolete documentation for helm init
  content/en/docs/helm/helm_init.md
Labels: size/M

#490 Fix "enironment" typo
  content/en/docs/topics/registries.md
Labels: size/XS

#492 docs: Missing parameter in command line
  content/en/docs/chart_template_guide/getting_started.md
Labels: bug, size/XS

#479 Adds advanced Helm techniques section
  content/en/docs/topics/advanced.md
Labels: size/L

#493 Helm 3.1.0 is out. Updating the listed version
  config.toml
Labels: size/XS

#491 fix `input-values` typo
  content/en/docs/topics/charts.md
Labels: awaiting review, size/XS

#498 Fix GitHub spelling
  CONTRIBUTING.md
  content/en/blog/2018-12-11-helm-hub.md
  content/en/blog/2019-06-10-get-helm-sh.md
  content/en/docs/community/related.md
  content/en/docs/topics/chart_repository.md
  content/en/docs/topics/plugins.md
  themes/helm/layouts/index.html
  themes/helm/layouts/partials/nav.html
Labels: bug, size/M

#500 docs(helm): Clarify GPG key selection for `package --sign`
  content/en/docs/topics/provenance.md
Labels: size/XS

#496 Adding a step to the release checklist to update the Helm website
  content/en/docs/community/release_checklist.md
Labels: size/XS

#495 v2.16.3 was released with tiller image updates.
  config.toml
Labels: size/XS

#503 Align menu icons hover effect on center
  themes/helm/assets/sass/helm-home.scss
Labels: size/XS

#510 Update values_files.md
  content/en/docs/chart_template_guide/values_files.md
Labels: size/S

#513 helm2 command changed as helm3 versioned
  content/en/docs/chart_template_guide/functions_and_pipelines.md
Labels: size/XS

#514 helm2 command changed as helm3 versioned
  content/en/docs/chart_template_guide/named_templates.md
Labels: size/XS

#515 notes_files page improvements some typo fix and old commands for helm…
  content/en/docs/chart_template_guide/notes_files.md
Labels: size/XS
