Repository helm/helm-www, pull requests merged in 2020-11, with the labels that each got.

#924 Fix code example
  content/en/docs/topics/plugins.md
Labels: size/XS

#905 [ko] Translate topics/chart-hooks into Korean
  content/ko/docs/topics/charts_hooks.md
Labels: size/L

#884 Adding Artifact Hub to replace Helm Hub in docs.
  content/en/docs/community/history.md
  content/en/docs/intro/using_helm.md
  content/en/docs/topics/v2_v3_migration.md
  i18n/en.toml
  themes/helm/layouts/index.html
  themes/helm/static/img/artifact-hub.jpg
Labels: size/S

#927 Specify the old locations being referred to
  content/en/blog/2020-10-26-new-location-stable-incubator-charts.md
Labels: size/XS

#915 [ko] Translate topic/rbac in korean
  content/ko/docs/topics/rbac.md
Labels: size/L

#917 Add Chinese doc
  content/zh/docs/chart_template_guide/accessing_files.md
  content/zh/docs/chart_template_guide/builtin_objects.md
  content/zh/docs/faq/_index.md
  content/zh/docs/howto/charts_tips_and_tricks.md
  content/zh/docs/intro/quickstart.md
  content/zh/docs/topics/advanced.md
  content/zh/docs/topics/chart_repository.md
  content/zh/docs/topics/charts.md
  content/zh/docs/topics/library_charts.md
  content/zh/docs/topics/permissions_sql_storage_backend.md
  content/zh/docs/topics/registries.md
  content/zh/docs/topics/version_skew.md
Labels: size/XXL

#919 [ko] Translate topic/advanced helm tech in Korean
  content/ko/docs/topics/advanced.md
Labels: size/L

#931 Clarify how to update sidebar.
  README.md
Labels: size/XS

#930 Adding deprecated APIs link to sidebar
  config.toml
  gulpfile.js
Labels: size/S

#929 Fix invalid examples of Helm template comments
  content/en/docs/chart_best_practices/templates.md
  content/en/docs/topics/library_charts.md
  content/ko/docs/chart_best_practices/templates.md
  content/ko/docs/topics/library_charts.md
Labels: size/S

#947 Adding release calendar redirect
  netlify.toml
Labels: size/XS

#948 Bumping Helm to 3.4.1
  config.toml
Labels: size/XS

#949 Adding post on new release process
  content/en/blog/2020-11-11-helm-release-process.md
Labels: size/S

#952 add last blog post on Helm 2 deprecation
  content/en/blog/2020-11-13-helm-2-becomes-unsupported.md
Labels: blog, size/S

#953 update inconsistent timeout definition
  content/en/docs/intro/using_helm.md
Labels: size/XS

#940 [zh] Add Chinese docs
  content/zh/docs/chart_template_guide/named_templates.md
  content/zh/docs/howto/chart_repository_sync_example.md
  content/zh/docs/intro/install.md
  content/zh/docs/intro/quickstart.md
  content/zh/docs/topics/advanced.md
  content/zh/docs/topics/chart_repository.md
  content/zh/docs/topics/charts.md
  content/zh/docs/topics/library_charts.md
  content/zh/docs/topics/provenance.md
  content/zh/docs/topics/registries.md
  content/zh/docs/topics/release_policy.md
  content/zh/docs/topics/version_skew.md
Labels: size/XL

#951 Add helm-git as related project
  content/en/docs/community/related.md
Labels: size/XS

#955 Translate several sections in faq page into Japanese
  content/ja/docs/faq/_index.md
Labels: size/L

#954 Add mentions of release calendar
  content/en/docs/community/release_checklist.md
  content/en/docs/topics/release_policy.md
  i18n/en.toml
  themes/helm/layouts/index.html
Labels: size/S

#876 Translating portion of accessing_files.md
  content/ko/docs/chart_template_guide/accessing_files.md
Labels: awaiting review, size/M, translation

#963 Add FreeBSD package installation instructions
  content/en/docs/intro/install.md
Labels: size/S

#964 Add link to OCI HIP from Registries page
  content/en/docs/topics/registries.md
Labels: size/XS
