Repository helm/helm-www, pull requests merged in 2020-04, with the labels that each got.

#554 Adding new blog post
  content/en/blog/2020-04-02-covid-19-extending-helm-v2-bug-fixes.md
Labels: size/S

#557 Adding docs on localizing content
  content/en/docs/community/history.md
  content/en/docs/community/localization.md
Labels: awaiting review, docs, size/M

#545 feat(chart_best_practices): Add details about --dry-run with CRDs
  content/en/docs/chart_best_practices/custom_resource_definitions.md
Labels: enhancement, size/XS

#560 Correct a typo
  content/en/docs/chart_template_guide/control_structures.md
Labels: size/XS

#561 Fix bad registry mediatype
  content/en/docs/topics/registries.md
Labels: size/XS

#542 feat(topics/advanced): Add the storage backend section
  content/en/docs/topics/advanced.md
Labels: enhancement, size/M

#562 fix(docs/topics): fix indentation in example
  content/en/docs/topics/charts.md
Labels: awaiting review, size/S

#566 Convert get started to Korean
  i18n/ko.toml
Labels: size/XS

#544 Clarify what the keep resource policy does
  content/en/docs/howto/charts_tips_and_tricks.md
Labels: size/S

#567 fix(docs): remove stale related documentation/projects
  content/en/docs/community/related.md
Labels: size/L

#565 Fixing kubectl command
  content/en/docs/faq/_index.md
Labels: size/XS

#568 translation of copy
  i18n/ko.toml
Labels: size/XS

#569 translation
  i18n/ko.toml
Labels: size/XS

#570 TranslationKor1
  i18n/ko.toml
Labels: size/S

#564 feat(docs): document `lookup`
  content/en/docs/chart_template_guide/functions_and_pipelines.md
Labels: size/M

#572 Specifies the order of the topics
  content/en/docs/topics/advanced.md
  content/en/docs/topics/architecture.md
  content/en/docs/topics/chart_repository.md
  content/en/docs/topics/chart_tests.md
  content/en/docs/topics/charts.md
  content/en/docs/topics/charts_hooks.md
  content/en/docs/topics/kubernetes_distros.md
  content/en/docs/topics/library_charts.md
  content/en/docs/topics/plugins.md
  content/en/docs/topics/provenance.md
  content/en/docs/topics/rbac.md
  content/en/docs/topics/registries.md
  content/en/docs/topics/v2_v3_migration.md
Labels: size/S

#573 Noting that README is displaed on hubs
  content/en/docs/topics/charts.md
Labels: size/XS

#582 Add og-image and meta
  themes/helm/layouts/partials/meta.html
  themes/helm/static/img/og-image.png
Labels: size/XS

#577 [#543] fix search box cropping bug
  themes/helm/assets/sass/docs-content.scss
  themes/helm/assets/sass/docs-sidebar.scss
Labels: bug, size/M

#584 feat(docs): add more `lookup` examples
  content/en/docs/chart_template_guide/functions_and_pipelines.md
Labels: size/S

#585 Add Blood Orange to contributors
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/bloodorange.png
Labels: size/XS

#590 Fix the IKS Helm link
  content/en/docs/topics/kubernetes_distros.md
Labels: bug, size/XS

#579 fix(charts): Update chart type section for better clarity
  content/en/docs/topics/charts.md
Labels: size/S

#588 [#583] adjust sidebar scrolling area
  themes/helm/assets/sass/docs-sidebar.scss
Labels: size/S

#593 en] uninstall or uninstall
  content/en/docs/intro/using_helm.md
Labels: size/XS

#592 Add required Linux Foundation copyright footer
  themes/helm/assets/sass/docs-footer.scss
  themes/helm/assets/sass/styles.scss
  themes/helm/layouts/404.html
  themes/helm/layouts/blog/list.html
  themes/helm/layouts/blog/single.html
  themes/helm/layouts/docs/helm/list.html
  themes/helm/layouts/docs/list.html
  themes/helm/layouts/docs/single.html
  themes/helm/layouts/index.html
  themes/helm/layouts/partials/footer-links.html
  themes/helm/layouts/partials/footer.html
Labels: size/L

#595 chore(docs): bump stable version to 3.2
  config.toml
Labels: docs, size/XS

#596 Remove reference to `helm home` command on plugins page
  content/en/docs/topics/plugins.md
Labels: size/S

#589 Translate intro/install.md in Korean
  content/ko/docs/intro/install.md
Labels: size/L

#576 Translate /docs/quickstart/ in Korean
  content/ko/docs/intro/quickstart.md
Labels: size/L

#599 Add IBM to contributors
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/ibm.png
Labels: size/XS

#594 Chart doc fixes
  content/en/docs/topics/charts.md
Labels: size/XS

#600 Sort the contributor list in alphabetical order
  themes/helm/layouts/partials/footer.html
Labels: awaiting review, size/S

#601 Disable typographer extension in markup parsing
  config.toml
Labels: size/XS

#602 Convert helm.sh links for theme into internal links
  themes/helm/layouts/partials/footer-links.html
  themes/helm/layouts/partials/footer-social.html
  themes/helm/layouts/partials/nav-fixed.html
  themes/helm/layouts/partials/nav.html
Labels: size/S

#605 Adding to the FAQ around Secrets vs ConfigMaps
  content/en/docs/faq/_index.md
Labels: size/XS

#604 Adding clarification about distros that work
  content/en/docs/topics/kubernetes_distros.md
Labels: size/S

#603 Clarify available doc versions
  config.toml
Labels: size/XS

#610 [language/ko] docs/intro/install.md minor edit
  content/ko/docs/intro/install.md
Labels: size/XS

#612 Adding Helm graduation blog post & blog-specific Twitter Cards
  config.toml
  content/en/blog/2020-04-30-celebrating-helms-cncf-graduation.md
  content/en/blog/images/helmgraduation-twitter.png
  content/en/blog/images/helmgraduation.png
  themes/helm/layouts/partials/meta.html
Labels: awaiting review, blog, size/M

#615 Add grad link
  content/en/blog/2020-04-30-celebrating-helms-cncf-graduation.md
Labels: size/XS
