Repository helm/helm-www, pull requests merged in 2020-03, with the labels that each got.

#516 Add link checker to site build
  .gitignore
  .htmltest.yml
  Makefile
  netlify.toml
  themes/helm/layouts/_default/_markup/render-link.html
Labels: size/M

#523 [#499] [#522] fix code block styling issues
  config.toml
  content/en/docs/topics/charts.md
  themes/helm/assets/sass/docs-content.scss
Labels: size/S

#518 match real output
  content/en/docs/chart_template_guide/getting_started.md
Labels: size/S

#520 List all global flags
  content/en/docs/topics/plugins.md
Labels: size/XS

#519 Add note about tested release
  content/en/docs/intro/install.md
Labels: size/XS

#527 set node version for builds using nvm
  .nvmrc
Labels: dependencies, size/XS

#517 Update JS packages
  package.json
  yarn.lock
Labels: size/XXL

#529 [v3 theme] fix events typo
  i18n/en.toml
Labels: awaiting review, size/XS

#531 fix sidebar contribution link
  themes/helm/layouts/partials/sidebar.html
Labels: size/XS

#506 Add details of shell auto-completion for plugins
  content/en/docs/topics/plugins.md
Labels: size/L

#534 Fixing broken link to chart template guide
  content/en/docs/chart_template_guide/getting_started.md
Labels: size/XS

#525 Updated the checklist sha245sum url
  content/en/docs/community/release_checklist.md
Labels: size/S

#526 feat(topic): Improve library charts documentation
  content/en/docs/topics/library_charts.md
Labels: in progress, size/L

#537 Added new line to fix formatting.
  content/en/docs/helm/helm_install.md
Labels: size/XS

#535 Add doc for `make release-notes`
  content/en/docs/community/release_checklist.md
Labels: awaiting review, size/S

#541 [#539] restore search on docs
  themes/helm/assets/js/app.js
  themes/helm/assets/sass/docs-content.scss
  themes/helm/layouts/partials/js.html
Labels: bug, docs, size/M

#528 [#524] fix left nav duplicated links
  content/en/docs/chart_best_practices/_index.md
  content/en/docs/chart_best_practices/conventions.md
  content/en/docs/chart_best_practices/custom_resource_definitions.md
  content/en/docs/chart_best_practices/dependencies.md
  content/en/docs/chart_best_practices/labels.md
  content/en/docs/chart_best_practices/pods.md
  content/en/docs/chart_best_practices/rbac.md
  content/en/docs/chart_best_practices/templates.md
  content/en/docs/chart_best_practices/values.md
  content/en/docs/faq/_index.md
  content/en/docs/glossary/_index.md
  themes/helm/layouts/partials/sidebar.html
Labels: bug, docs, in progress, size/M

#532 Updating the developer and source docs
  content/en/docs/community/developers.md
  content/en/docs/intro/install.md
Labels: size/XS

#550 Snapcraft installation instructions added
  content/en/docs/intro/install.md
  themes/helm/layouts/index.html
Labels: size/S
