Repository helm/helm-www, pull requests merged in 2020-06, with the labels that each got.

#656 [translation/ko] docs/community/_index.md
  content/ko/docs/community/_index.md
Labels: size/XS

#655 [translation/ko] docs/faq/_index.md
  content/ko/docs/faq/_index.md
Labels: size/XL

#654 [translation/ko] docs/topics/_index.md
  content/ko/docs/topics/_index.md
Labels: size/XS

#653 [translation/ko] docs/intro/_index.md
  content/ko/docs/intro/_index.md
Labels: size/XS

#647 [translation/ko] i18n/ko.toml
  i18n/ko.toml
Labels: size/M

#651 [translation/ko] docs/glossary/_index.md
  content/ko/docs/glossary/_index.md
Labels: size/L

#648 [translation/ko] docs/_index.md
  content/ko/docs/_index.md
Labels: size/S

#652 [translation/ko] docs/howto/_index.md
  content/ko/docs/howto/_index.md
Labels: size/S

#639 Add ConfigMap backend details to steps for updating a release manifest
  content/en/docs/topics/kubernetes_apis.md
Labels: size/M

#659 [translation/ko] docs/chart_best_practices/conventions.md
  content/ko/docs/chart_best_practices/conventions.md
Labels: size/M

#660 [translation/ko] docs/chart_best_practices/custom_resource_definitions.md
  content/ko/docs/chart_best_practices/custom_resource_definitions.md
Labels: size/M

#662 [translation/ko] docs/chart_best_practices/some_files.md
  content/ko/docs/chart_best_practices/dependencies.md
  content/ko/docs/chart_best_practices/labels.md
  content/ko/docs/chart_best_practices/pods.md
  content/ko/docs/chart_best_practices/rbac.md
  content/ko/docs/chart_best_practices/templates.md
  content/ko/docs/chart_best_practices/values.md
Labels: size/XL

#664 Community banner update
  i18n/en.toml
  themes/helm/assets/sass/docs-topbar.scss
  themes/helm/assets/sass/helm-home.scss
  themes/helm/layouts/partials/banner.html
Labels: awaiting review, size/S

#669 Add title to helm upgrade docs.
  content/en/docs/helm/helm_upgrade.md
Labels: size/XS

#673 innaugural → inaugural (community history)
  content/en/docs/community/history.md
Labels: bug, size/XS

#488 add notes for depricated commands
  content/en/docs/helm/helm_delete.md
  content/en/docs/helm/helm_inspect.md
Labels: awaiting review, proposal, size/S

#668 Update charts.md
  content/en/docs/topics/charts.md
Labels: size/XS

#481 feat(topics): Helm Version Support Policy
  content/en/docs/topics/version_skew.md
Labels: enhancement, size/M

#597 Add helm-secrets
  content/en/docs/community/related.md
Labels: size/XS

#676 Updating current versions for website
  config.toml
Labels: size/XS

#677 Moving explanation to where it makes sense.
  content/en/docs/chart_template_guide/getting_started.md
Labels: size/XS

#630 update `helm install` & `helm status` output
  content/en/docs/intro/using_helm.md
Labels: size/L

#507 Proofread documentation
  content/en/docs/chart_best_practices/custom_resource_definitions.md
  content/en/docs/chart_best_practices/dependencies.md
  content/en/docs/chart_best_practices/labels.md
  content/en/docs/chart_best_practices/rbac.md
  content/en/docs/chart_best_practices/values.md
  content/en/docs/chart_template_guide/subcharts_and_globals.md
  content/en/docs/chart_template_guide/values_files.md
  content/en/docs/chart_template_guide/variables.md
  content/en/docs/chart_template_guide/wrapping_up.md
  content/en/docs/howto/chart_repository_sync_example.md
  content/en/docs/howto/charts_tips_and_tricks.md
  content/en/docs/intro/install.md
  content/en/docs/intro/using_helm.md
  content/en/docs/topics/advanced.md
  content/en/docs/topics/charts.md
  content/en/docs/topics/kubernetes_distros.md
  content/en/docs/topics/plugins.md
  content/en/docs/topics/rbac.md
  content/en/docs/topics/v2_v3_migration.md
Labels: size/L

#663 [translation/ko] docs/faq/_index.md (partial)
  content/ko/docs/faq/_index.md
Labels: size/L

#665 [translation/ko] docs/helm/_index.md
  content/ko/docs/helm/_index.md
Labels: size/S

#666 [translation/ko] docs/topics/architecture.md
  content/ko/docs/topics/architecture.md
Labels: size/M

#671 [translation/ko] docs/chart_template_guide/* (partial)
  content/ko/docs/chart_template_guide/_index.md
  content/ko/docs/chart_template_guide/accessing_files.md
  content/ko/docs/chart_template_guide/builtin_objects.md
  content/ko/docs/chart_template_guide/control_structures.md
  content/ko/docs/chart_template_guide/data_types.md
  content/ko/docs/chart_template_guide/debugging.md
  content/ko/docs/chart_template_guide/functions_and_pipelines.md
  content/ko/docs/chart_template_guide/getting_started.md
  content/ko/docs/chart_template_guide/helm_ignore_file.md
  content/ko/docs/chart_template_guide/named_templates.md
  content/ko/docs/chart_template_guide/notes_files.md
  content/ko/docs/chart_template_guide/subcharts_and_globals.md
  content/ko/docs/chart_template_guide/values_files.md
  content/ko/docs/chart_template_guide/variables.md
  content/ko/docs/chart_template_guide/wrapping_up.md
  content/ko/docs/chart_template_guide/yaml_techniques.md
Labels: size/XXL

#678 [translation/ko] docs/community/history.md
  content/ko/docs/community/history.md
Labels: size/S

#685 Update charts_tips_and_tricks.md
  content/en/docs/howto/charts_tips_and_tricks.md
Labels: size/XS

#692 Enforce https in URLs
  i18n/en.toml
  i18n/ko.toml
  i18n/zh.toml
  themes/helm/layouts/404.html
  themes/helm/layouts/index.html
  themes/helm/layouts/partials/footer-social.html
  themes/helm/layouts/partials/footer.html
Labels: size/S

#695 Add list of tests to update as part of releasing a new version
  content/en/docs/community/release_checklist.md
Labels: size/S

#696 improve language switching
  config.toml
  i18n/en.toml
  i18n/ko.toml
  themes/helm/assets/sass/docs-topbar.scss
  themes/helm/layouts/partials/nav-fixed.html
  themes/helm/layouts/partials/nav.html
Labels: awaiting review, docs, size/M

#697 3.2.4 released
  config.toml
Labels: size/XS

#699 [v2] update gulp task to fix hyphens in environment variables
  config.toml
  gulpfile.js
Labels: awaiting review, docs, size/XS

#698 Add chart alias
  content/en/docs/topics/charts.md
Labels: awaiting review, size/XS

#702 Updating v2 in docs
  config.toml
Labels: size/XS

#693 [ko] chart_best_practices/labels.md (partial)
  content/ko/docs/chart_best_practices/labels.md
Labels: size/M

#700 Adding documentation on template functions
  content/en/docs/chart_template_guide/accessing_files.md
  content/en/docs/chart_template_guide/control_structures.md
  content/en/docs/chart_template_guide/function_list.md
  content/en/docs/chart_template_guide/named_templates.md
  content/en/docs/chart_template_guide/variables.md
Labels: awaiting review, size/XXL

#679 [ko] chart_best_practices/custom_resource_definitions.md
  content/ko/docs/chart_best_practices/custom_resource_definitions.md
Labels: size/M

#703 Adding helm description and links
  content/en/docs/_index.md
Labels: size/XS

#708 Fixing navigation greating links that go to nowhere
  themes/helm/layouts/partials/nav-fixed.html
  themes/helm/layouts/partials/nav.html
Labels: size/XS

#691 [ko] chart_best_practices/dependencies.md
  content/ko/docs/chart_best_practices/dependencies.md
Labels: size/M

#690 [ko] helm-www/config.toml (languages.ko.)
  config.toml
Labels: size/S

#701 [#553] add prev and next links to docs
  themes/helm/assets/sass/docs-content.scss
  themes/helm/layouts/docs/single.html
Labels: awaiting review, size/M

#710 [#658] add netlify redirect for developing_charts
  netlify.toml
Labels: awaiting review, size/XS

#641 Add Apt (Deb/Ubuntu) installation instructions
  content/en/docs/faq/_index.md
  content/en/docs/intro/install.md
Labels: size/S

#713 Update the install instructions for Helm
  content/en/docs/faq/_index.md
  content/en/docs/intro/install.md
Labels: awaiting review, size/M

#714 Replace zh. toml with the latest en.toml
  i18n/zh.toml
Labels: size/S

#716 fix community_slack_join display
  themes/helm/layouts/index.html
Labels: size/XS

#712 [ko] ko.toml (partial)
  i18n/ko.toml
Labels: size/S

#711 [ko] chart_best_practices/pods
  content/ko/docs/chart_best_practices/pods.md
Labels: size/M, translation

#722 Added the Terraform Helm provider to Additional Tools
  content/en/docs/community/related.md
Labels: size/XS

#723 Clarify path for template directory
  content/en/docs/chart_template_guide/getting_started.md
  content/ko/docs/chart_template_guide/getting_started.md
Labels: size/S

#727 Fixing the release checklist
  content/en/docs/community/release_checklist.md
Labels: size/XS

#724 Clarify chart testing
  content/en/docs/topics/chart_tests.md
  content/en/docs/topics/charts.md
Labels: size/M

#729 [#726] add a note about helm init
  content/en/docs/helm/helm_init.md
Labels: awaiting review, docs, size/XS

#731 bump hugo to 0.73.0
  netlify.toml
Labels: size/XS

#733 Provide go package lookup metadata for individual packages
  netlify.toml
Labels: size/S
