Repository helm/helm-www, pull requests merged in 2020-10, with the labels that each got.

#850 Translate topic : 'chart tests' in Korean
  content/ko/docs/topics/chart_tests.md
Labels: awaiting review, size/L, translation

#853 Translate CONTRIBUTING.md into Korean
  CONTRIBUTING-ko.md
Labels: awaiting review, size/L, translation

#879 Fix command for enabling Helm v3 in MicroK8s
  content/en/docs/topics/kubernetes_distros.md
  content/ko/docs/topics/kubernetes_distros.md
Labels: size/XS

#880 [minor edit] removing unnecessary special character
  CONTRIBUTING-ko.md
Labels: size/XS

#859 Translate index file in chart_best_practices in Korean
  content/ko/docs/chart_best_practices/_index.md
Labels: awaiting review, size/S, translation

#866 Translate topic : v2 v3 migration
  content/ko/docs/topics/v2_v3_migration.md
Labels: awaiting review, size/L, translation

#882 Adding post on the move from the helm to artifact hub
  content/en/blog/2020-10-07-helm-hub-moving-artifact-hub.md
Labels: size/M

#881 Clarifications in the v2 to v3 migration doc
  content/en/docs/topics/v2_v3_migration.md
Labels: size/S

#878 Translate 'charts_tips_and_tricks' into Japanese.
  content/ja/docs/howto/charts_tips_and_tricks.md
Labels: size/L

#885 extend helmignore description examples
  content/en/docs/chart_template_guide/helm_ignore_file.md
Labels: size/S

#886 Fix typo in function_list.md
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#825 Translate topics/registries.md into Korean
  content/ko/docs/topics/registries.md
Labels: awaiting review, size/L, translation

#887 Correct the wrong Korean term
  content/ko/docs/chart_template_guide/getting_started.md
  content/ko/docs/community/related.md
Labels: awaiting review, size/S, translation

#888 Update the Korean banner
  i18n/ko.toml
Labels: awaiting review, size/XS, translation

#844 Translate 'helm pull' command in Korean
  content/ko/docs/helm/helm_pull.md
Labels: awaiting review, size/M, translation

#865 Translate 'helm verify' command into Korean
  content/ko/docs/helm/helm_verify.md
Labels: awaiting review, size/M, translation

#890 Translate blog(20200813) in Korean
  content/ko/blog/2020-08-13-helm-v2-deprecation-timeline.md
Labels: awaiting review, size/M, translation

#901 [blog] add 5th birthday blog post
  content/en/blog/2020-10-19-helm-turns-five.md
  content/en/blog/images/happy-5th.png
  content/en/blog/images/octocat.png
Labels: blog, size/M

#897 update repository URLs
  content/en/docs/faq/_index.md
  content/en/docs/intro/quickstart.md
  content/en/docs/intro/using_helm.md
  content/en/docs/topics/library_charts.md
  content/ja/docs/faq/_index.md
  content/ja/docs/intro/quickstart.md
  content/ja/docs/intro/using_helm.md
  content/ko/docs/faq/_index.md
  content/ko/docs/intro/quickstart.md
  content/ko/docs/intro/using_helm.md
  content/ko/docs/topics/library_charts.md
  content/zh/docs/faq/_index.md
  content/zh/docs/intro/quickstart.md
Labels: size/M

#877 Clarifying random strings between templates
  content/en/docs/howto/charts_tips_and_tricks.md
Labels: size/XS

#902 Fixing paths
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_zsh.md
Labels: size/S

#900 Translate helm_completion_bash/zsh.md into korean
  content/ko/docs/helm/helm_completion_bash.md
  content/ko/docs/helm/helm_completion_zsh.md
Labels: size/L

#896 Translate blog(20191113) in Korean
  content/ko/blog/2019-11-13-helm-3-released.md
Labels: awaiting review, size/L, translation

#894 Translate blog(20191115) in Korean
  content/ko/blog/2019-11-15-helm-at-cloudnativecon.md
Labels: awaiting review, size/S, translation

#895 Translate README.md into Korean
  README-ko.md
Labels: awaiting review, size/M, translation

#906 Release v3.4 and v2.17 post and config
  config.toml
  content/en/blog/2020-10-26-new-location-stable-incubator-charts.md
Labels: size/M

#869 Add next release date as per HIP 0002
  config.toml
  content/en/docs/community/release_checklist.md
  content/en/docs/topics/release_policy.md
  content/en/docs/topics/version_skew.md
  i18n/en.toml
  themes/helm/layouts/index.html
Labels: in progress, size/L

#911 [en] missing 'request'
  content/en/docs/topics/charts_hooks.md
Labels: size/XS

#893 Translate blog(20200420) in Korean
  content/ko/blog/2020-04-02-covid-19-extending-helm-v2-bug-fixes.md
Labels: awaiting review, size/S, translation

#870 Update supported versions
  content/en/docs/topics/version_skew.md
Labels: in progress, size/XS

#891 Translate blog(20200430) in Korean
  content/ko/blog/2020-04-30-celebrating-helms-cncf-graduation.md
  content/ko/blog/images/helm-2to3.png
  content/ko/blog/images/helmgraduation-twitter.png
  content/ko/blog/images/helmgraduation.png
Labels: awaiting review, size/M, translation

#916 Add Charts repo deprecation blog
  content/en/blog/2020-10-30-charts-repo-deprecation.md
Labels: size/M

#923 Blog addition amendments
  content/en/blog/2020-10-30-charts-repo-deprecation.md
Labels: size/XS

#922 Mention to run proper version to generate docs
  README.md
Labels: size/XS

#920 [ja] Translate community/localization in Japanese
  content/ja/docs/community/localization.md
Labels: size/L

#841 Translate docs/faq/_index.md into Korean
  content/ko/docs/faq/_index.md
Labels: awaiting review, size/XXL, translation

#908 [ko] Translate topic-release policy in Korean
  content/ko/docs/topics/release_policy.md
Labels: size/M

#910 [ko] Translate topics/kubernetes_api in Korean
  content/ko/docs/topics/kubernetes_apis.md
Labels: size/L
