Repository helm/helm-www, pull requests merged in 2021-04, with the labels that each got.

#1061 fix(release_checklist): release branches are `release-X.Y`
  content/en/docs/community/release_checklist.md
  content/ko/docs/community/release_checklist.md
  content/zh/docs/community/release_checklist.md
Labels: size/S

#1062 Updating version number
  config.toml
Labels: size/XS

#1066 Spanish translation
  config.toml
  content/es/docs/_index.md
  content/es/docs/intro/_index.md
  content/es/docs/intro/install.md
  content/es/docs/intro/quickstart.md
  content/es/docs/intro/using_helm.md
  i18n/es.toml
Labels: size/XXL

#1063 Updated Chinese translation, a typo/更新中文翻译，一个错别字
  content/zh/docs/howto/charts_tips_and_tricks.md
Labels: size/XS

#1044 [ko] Translate topics/charts.md into Korean
  content/ko/docs/topics/charts.md
Labels: size/XL, translation

#1070 [zh] Fix typo
  content/zh/docs/faq/_index.md
Labels: size/XS

#1071 Clarifying where CLI docs are edited.
  content/en/docs/community/developers.md
Labels: size/XS

#1068 Updating for 3.5.4
  config.toml
Labels: size/XS

#1067 Update to match all languages
  i18n/fr.toml
Labels: size/XS

#1072 Translate docs/howto to Spanish
  content/es/docs/_index.md
  content/es/docs/howto/_index.md
  content/es/docs/howto/chart_repository_sync_example.md
  content/es/docs/howto/charts_tips_and_tricks.md
  i18n/es.toml
Labels: size/L

#1073 [zh] Update Chinese docs
  content/zh/docs/community/developers.md
Labels: size/XS

#1074 Language Menu Adjustments
  config.toml
  themes/helm/assets/sass/docs-topbar.scss
  themes/helm/assets/sass/helm-home.scss
  themes/helm/assets/sass/helm-layout.scss
  themes/helm/layouts/partials/nav-fixed.html
  themes/helm/layouts/partials/nav.html
Labels: design, size/M

#1075 [es] Translate docs/topics/charts to Spanish
  content/es/docs/_index.md
  content/es/docs/howto/_index.md
  content/es/docs/howto/chart_repository_sync_example.md
  content/es/docs/topics/_index.md
  content/es/docs/topics/charts.md
Labels: size/XXL

#1076 [es] Translate docs/topics/charts_hooks to Spanish
  content/es/docs/topics/charts_hooks.md
Labels: size/L

#1077 [es] Translate docs/topics/charts_tests to Spanish
  content/es/docs/topics/chart_tests.md
Labels: size/L

#1078 docs(fix): modify Chinese docs
  content/zh/docs/chart_best_practices/values.md
  content/zh/docs/chart_template_guide/function_list.md
  content/zh/docs/chart_template_guide/variables.md
  content/zh/docs/chart_template_guide/yaml_techniques.md
  content/zh/docs/howto/charts_tips_and_tricks.md
Labels: size/M

#1082 fix Chinese translation
  content/zh/docs/chart_template_guide/subcharts_and_globals.md
Labels: size/XS

#1080 docs(fix): modify chinese docs
  content/zh/docs/howto/chart_repository_sync_example.md
Labels: size/XS

#1083 add new plugin
  content/en/docs/community/related.md
Labels: size/XS

#1084 [es] Translate docs/topics/library_charts to Spanish
  content/es/docs/_index.md
  content/es/docs/howto/_index.md
  content/es/docs/topics/charts.md
  content/es/docs/topics/library_charts.md
Labels: size/L

#1085 [zh] Fix typo
  content/zh/docs/faq/_index.md
Labels: size/XS

#1087 [zh] Update Chinese docs
  content/zh/docs/community/related.md
Labels: size/XS
