Repository helm/helm-www, pull requests merged in 2021-02, with the labels that each got.

#1013 Add patch release cancellation conditions
  content/en/docs/topics/release_policy.md
Labels: size/XS

#1016 Adjust docs to reflect Artifact Hub & helm/charts updates
  content/en/docs/chart_template_guide/builtin_objects.md
  content/en/docs/chart_template_guide/wrapping_up.md
  content/en/docs/community/release_checklist.md
  content/en/docs/howto/charts_tips_and_tricks.md
  content/en/docs/intro/quickstart.md
  content/en/docs/intro/using_helm.md
  content/en/docs/topics/chart_repository.md
  content/en/docs/topics/charts.md
  content/en/docs/topics/library_charts.md
  content/en/docs/topics/provenance.md
Labels: size/M

#1014 [zh] Add Chinese docs
  content/zh/docs/chart_template_guide/notes_files.md
  content/zh/docs/chart_template_guide/subcharts_and_globals.md
  content/zh/docs/chart_template_guide/variables.md
  content/zh/docs/chart_template_guide/wrapping_up.md
  content/zh/docs/chart_template_guide/yaml_techniques.md
  content/zh/docs/intro/using_helm.md
  content/zh/docs/topics/chart_tests.md
  content/zh/docs/topics/charts.md
  content/zh/docs/topics/charts_hooks.md
  content/zh/docs/topics/library_charts.md
  content/zh/docs/topics/provenance.md
  content/zh/docs/topics/registries.md
  content/zh/docs/topics/release_policy.md
Labels: size/XXL

#1019 fixed a typo
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#1023 Fix typo
  content/ja/docs/intro/quickstart.md
Labels: size/XS

#1026 isKind -> kindIs
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#1024 Unify the translation of 'chart'
  content/ja/docs/chart_template_guide/_index.md
  content/ja/docs/intro/quickstart.md
Labels: size/XS

#1027 Bumping version to 3.5.2
  config.toml
Labels: size/XS

#1028 Fix typo
  content/ja/docs/community/localization.md
Labels: size/XS

#1022 Improve wording
  content/en/docs/chart_template_guide/getting_started.md
Labels: size/XS

#1021 [zh] Add Chinese docs
  content/zh/docs/_index.md
  content/zh/docs/chart_best_practices/custom_resource_definitions.md
  content/zh/docs/chart_template_guide/builtin_objects.md
  content/zh/docs/chart_template_guide/debugging.md
  content/zh/docs/chart_template_guide/function_list.md
  content/zh/docs/chart_template_guide/subcharts_and_globals.md
  content/zh/docs/chart_template_guide/wrapping_up.md
  content/zh/docs/howto/charts_tips_and_tricks.md
  content/zh/docs/intro/install.md
  content/zh/docs/intro/quickstart.md
  content/zh/docs/intro/using_helm.md
  content/zh/docs/topics/architecture.md
  content/zh/docs/topics/chart_repository.md
  content/zh/docs/topics/chart_tests.md
  content/zh/docs/topics/charts.md
  content/zh/docs/topics/kubernetes_apis.md
  content/zh/docs/topics/kubernetes_distros.md
  content/zh/docs/topics/library_charts.md
  content/zh/docs/topics/plugins.md
  content/zh/docs/topics/provenance.md
  content/zh/docs/topics/rbac.md
  content/zh/docs/topics/v2_v3_migration.md
Labels: size/XL
