Repository helm/helm-www, pull requests merged in 2021-05, with the labels that each got.

#1088 Add backticks around .Values.who
  content/en/docs/howto/charts_tips_and_tricks.md
Labels: size/XS

#1089 Update Chinese doc
  content/zh/docs/howto/charts_tips_and_tricks.md
Labels: size/XS

#1092 docs(bug): fix the formatting of i18n menu when scrolling
  themes/helm/layouts/partials/nav-fixed.html
  themes/helm/layouts/partials/nav-i18n.html
  themes/helm/layouts/partials/nav-logo.html
  themes/helm/layouts/partials/nav-versioning.html
  themes/helm/layouts/partials/nav.html
Labels: awaiting review, size/L

#1017 Update quickstart guide to use non-deprecated repo
  content/en/docs/intro/quickstart.md
Labels: size/M

#1093 [es] Translate docs/topics/provenance to Spanish
  content/es/docs/topics/provenance.md
Labels: size/L

#1095 Add Greek Language
  config.toml
  content/gr/docs/_index.md
  i18n/gr.toml
Labels: size/L

#1099 Link to a maintained fork of helm-unittests
  content/en/docs/community/related.md
Labels: size/XS

#1097 [zh] Update Chinese docs
  content/zh/docs/chart_template_guide/named_templates.md
  content/zh/docs/intro/quickstart.md
Labels: size/M

#1102 [zh] Update Chinese doc
  content/zh/docs/community/related.md
Labels: size/XS

#1105 docs: faq structure update
  content/en/docs/faq/_index.md
  content/en/docs/faq/changes_since_helm2.md
  content/en/docs/faq/installing.md
  content/en/docs/faq/troubleshooting.md
  content/en/docs/faq/uninstalling.md
Labels: size/XXL

#1103 Greek: Add translated files to docs
  content/gr/docs/chart_best_practices/_index.md
  content/gr/docs/chart_best_practices/conventions.md
  content/gr/docs/chart_best_practices/dependencies.md
Labels: size/L

#1107 add adopt plugin
  content/en/docs/community/related.md
Labels: size/XS

#1098 Initial German Translation
  config.toml
  content/de/docs/_index.md
  content/de/docs/faq/_index.md
  content/de/docs/faq/changes_since_helm2.md
  content/de/docs/faq/installing.md
  content/de/docs/faq/troubleshooting.md
  content/de/docs/faq/uninstalling.md
  content/de/docs/glossary/_index.md
  content/de/docs/howto/_index.md
  content/de/docs/howto/chart_repository_sync_example.md
  content/de/docs/howto/charts_tips_and_tricks.md
  content/de/docs/intro/_index.md
  content/de/docs/intro/install.md
  content/de/docs/intro/quickstart.md
  content/de/docs/intro/using_helm.md
  i18n/de.toml
  themes/helm/assets/sass/docs-topbar.scss
Labels: size/XXL, translation

#928 Add documentation for Chart Releaser Action
  content/en/docs/howto/chart_releaser_action.md
  content/en/docs/topics/chart_repository.md
Labels: size/L

#1111 Adjust weight for page
  content/en/docs/howto/chart_releaser_action.md
Labels: size/XS

#1112 Capitalize C, and noted it's in other langs as well
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#1113 Remove outdated directory name constraint info
  content/en/docs/chart_best_practices/conventions.md
  content/gr/docs/chart_best_practices/conventions.md
  content/ja/docs/chart_best_practices/conventions.md
  content/ko/docs/chart_best_practices/conventions.md
  content/zh/docs/chart_best_practices/conventions.md
Labels: size/S

#1114 [zh] Add Chinese docs
  content/zh/docs/chart_template_guide/function_list.md
  content/zh/docs/community/related.md
  content/zh/docs/howto/chart_releaser_action.md
  content/zh/docs/topics/chart_repository.md
Labels: size/M

#1116 docs: fix various typos in function_list.md
  content/en/docs/chart_template_guide/function_list.md
Labels: size/S

#1115 More grammar/style fixes in function_list
  content/en/docs/chart_template_guide/function_list.md
Labels: size/M

#1119 docs: fix chinese expression
  content/zh/docs/intro/using_helm.md
Labels: size/XS

#1117 [zh] Update Chinese doc
  content/zh/docs/chart_template_guide/function_list.md
Labels: size/M

#1120 Update for v3.6.0 release
  config.toml
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_fish.md
  content/en/docs/helm/helm_completion_zsh.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_env.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_all.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_notes.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_uninstall.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_pull.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_search_hub.md
  content/en/docs/helm/helm_search_repo.md
  content/en/docs/helm/helm_show.md
  content/en/docs/helm/helm_show_all.md
  content/en/docs/helm/helm_show_chart.md
  content/en/docs/helm/helm_show_readme.md
  content/en/docs/helm/helm_show_values.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_uninstall.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
Labels: size/L
