Repository helm/helm-www, pull requests merged in 2021-09, with the labels that each got.

#1184 [pt] Adding Helm Install and Completion Command
  content/pt/docs/helm/helm_completion.md
  content/pt/docs/helm/helm_completion_bash.md
  content/pt/docs/helm/helm_completion_fish.md
  content/pt/docs/helm/helm_completion_zsh.md
  content/pt/docs/helm/helm_create.md
  content/pt/docs/helm/helm_install.md
Labels: size/L

#1182 Add Flux to Helm docs under Community > Related Projects > Tools
  content/en/docs/community/related.md
Labels: size/M

#1188 [pt] Updating references to Portuguese commands
  content/pt/docs/helm/helm.md
Labels: size/XS

#1185 Adds CRDs Caveats in Helm Install and Upgrade Commands
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_upgrade.md
Labels: size/XS

#1183 Make `version` optional for dependencies
  content/en/docs/topics/charts.md
Labels: size/XS

#1190 Revert "Make `version` optional for dependencies"
  content/en/docs/topics/charts.md
Labels: size/XS

#1193 [#1192] [zh] fix broken link in chart_repository page
  content/zh/docs/topics/chart_repository.md
Labels: bug, size/XS

#1194 Improve site for mobile screens
  themes/helm/assets/js/app.js
  themes/helm/assets/sass/docs-responsive.scss
  themes/helm/assets/sass/docs-sidebar.scss
  themes/helm/assets/sass/docs-topbar.scss
  themes/helm/layouts/partials/nav-i18n.html
  themes/helm/layouts/partials/nav-versioning.html
  themes/helm/layouts/partials/nav.html
  themes/helm/layouts/partials/sidebar.html
Labels: size/L

#1195 [zh] Update Chinese docs
  content/zh/docs/chart_best_practices/dependencies.md
  content/zh/docs/community/related.md
  content/zh/docs/faq/_index.md
  content/zh/docs/helm/helm_install.md
  content/zh/docs/helm/helm_upgrade.md
  content/zh/docs/howto/charts_tips_and_tricks.md
Labels: size/L

#1197 s/master/main/g
  content/en/docs/community/release_checklist.md
Labels: size/S

#1198 helm 3.7.0
  config.toml
  content/en/docs/topics/version_skew.md
Labels: size/XS

#1201 [zh] Update Chinese docs
  content/zh/docs/community/release_checklist.md
  content/zh/docs/topics/version_skew.md
Labels: size/S

#1205 Replace `master` with `main` where possible
  CONTRIBUTING-ko.md
  CONTRIBUTING.md
  README-ko.md
  README.md
  content/code/helm-v3.md
  content/code/helm.md
  content/de/docs/intro/install.md
  content/en/blog/2018-09-07-new-gov-and-elections.md
  content/en/blog/2018-09-25-chart-testing-intro.md
  content/en/blog/2019-11-04-helm-security-audit-results.md
  content/en/blog/2020-04-02-covid-19-extending-helm-v2-bug-fixes.md
  content/en/blog/2020-11-11-helm-release-process.md
  content/en/blog/2021-03-05-second-security-audit/index.md
  content/en/code/helm-v3.md
  content/en/code/helm.md
  content/en/docs/community/developers.md
  content/en/docs/community/localization.md
  content/en/docs/intro/install.md
  content/en/docs/topics/chart_repository.md
  content/en/docs/topics/registries.md
  content/es/docs/intro/install.md
  content/fr/docs/intro/install.md
  content/ja/docs/community/localization.md
  content/ja/docs/intro/install.md
  content/ko/blog/2020-04-02-covid-19-extending-helm-v2-bug-fixes.md
  content/ko/docs/community/developers.md
  content/ko/docs/community/history.md
  content/ko/docs/community/localization.md
  content/ko/docs/community/release_checklist.md
  content/ko/docs/intro/install.md
  content/ko/docs/topics/registries.md
  content/pt/docs/intro/install.md
  content/ru/docs/intro/install.md
  content/zh/docs/community/developers.md
  content/zh/docs/community/localization.md
  content/zh/docs/intro/install.md
  content/zh/docs/topics/registries.md
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/gr.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/pt.toml
  i18n/ru.toml
  i18n/zh.toml
  themes/helm/layouts/partials/footer-links.html
Labels: size/L

#1206 Improve rendering of commands for shell completion in translations
  content/ko/docs/helm/helm_completion_bash.md
  content/ko/docs/helm/helm_completion_fish.md
  content/ko/docs/helm/helm_completion_zsh.md
  content/zh/docs/helm/helm_completion_bash.md
  content/zh/docs/helm/helm_completion_fish.md
  content/zh/docs/helm/helm_completion_zsh.md
Labels: size/M

#1211 docs(FIX): Update helm-gcs repo link after project migration
  content/en/docs/community/related.md
  content/ko/docs/community/related.md
  content/zh/docs/community/related.md
Labels: size/XS

#1212 fix: wrong URL to mapkubeapis
  content/en/docs/topics/kubernetes_apis.md
  content/ko/docs/topics/kubernetes_apis.md
  content/zh/docs/topics/kubernetes_apis.md
Labels: size/L
