Repository helm/helm-www, pull requests merged in 2021-08, with the labels that each got.

#1161 [zh] Update Chinese doc
  content/zh/docs/intro/quickstart.md
Labels: size/XS

#1162 [pt] Adding Portuguese Language
  config.toml
  content/pt/docs/_index.md
  content/pt/docs/community/_index.md
  content/pt/docs/howto/_index.md
  content/pt/docs/intro/_index.md
  content/pt/docs/topics/_index.md
  i18n/pt.toml
Labels: size/L

#1164 [pt] Adding installation page
  content/pt/docs/intro/install.md
  i18n/pt.toml
Labels: size/L

#1163 Add documentation for GitLab Chart Repo
  content/en/docs/topics/chart_repository.md
Labels: size/XS

#1165 Updates on chain of trust/sigstore
  content/en/docs/community/related.md
  content/en/docs/topics/provenance.md
  content/es/docs/topics/provenance.md
  content/ko/docs/topics/provenance.md
  content/zh/docs/topics/provenance.md
Labels: size/S

#1166 Add details about Capabilities.HelmVersion
  content/en/docs/chart_template_guide/builtin_objects.md
Labels: size/XS

#1168 Fix error about dependency chart format
  content/en/docs/topics/charts.md
Labels: size/XS

#1167 [zh] Update Chinese docs
  content/zh/docs/chart_template_guide/builtin_objects.md
  content/zh/docs/community/related.md
  content/zh/docs/topics/chart_repository.md
Labels: size/S

#1169 [pt] Adding Portuguese Quickstart Guide
  content/pt/docs/intro/quickstart.md
Labels: size/L

#1170 [zh] Update Chinese doc
  content/zh/docs/topics/charts.md
Labels: size/XS

#1173 Adding FAQ entry for Tiller download issues
  content/en/docs/faq/troubleshooting.md
Labels: size/M

#1176 [pt] Adding Portuguese Glossary
  content/pt/docs/glossary/_index.md
  content/pt/docs/intro/install.md
  content/pt/docs/intro/quickstart.md
Labels: size/L

#1179 [pt] Adding Helm Commands (index + create)
  content/pt/docs/helm/_index.md
  content/pt/docs/helm/helm.md
  content/pt/docs/helm/helm_create.md
Labels: size/L
