Repository helm/helm-www, pull requests merged in 2021-12, with the labels that each got.

#1238 [ja] translate chart_best_practices/values.md into Japanese
  content/ja/docs/chart_best_practices/values.md
Labels: size/L

#1226 fix the translation problem
  content/zh/docs/chart_template_guide/yaml_techniques.md
Labels: size/XS

#1174 Docs for template function "index" on lists
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#1233 clarify pre-release version constraints
  content/en/docs/chart_best_practices/dependencies.md
Labels: size/S

#1234 [zh] Fix typo
  content/zh/docs/chart_template_guide/function_list.md
Labels: size/XS

#1237 [zh] Update Chinese docs
  content/zh/docs/topics/registries.md
Labels: size/L

#1232 `and` and `or` functions can take many arguments
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#1236 fix #1235 , Helm Chart as a Glossary when translated into Chinese
  i18n/zh.toml
Labels: awaiting review, size/S

#1245 Update Chinese docs.
  content/zh/docs/chart_best_practices/dependencies.md
  content/zh/docs/chart_template_guide/function_list.md
Labels: size/S

#1246 Update named_templates.md
  content/zh/docs/chart_template_guide/named_templates.md
Labels: size/XS

#1247 [ja] Translate community/developers.md
  content/ja/docs/community/developers.md
Labels: size/L

#1248 Updating to v3.7.2 of Helm
  config.toml
Labels: size/XS

#1249 Added note precreating namespace or repository for helm push
  content/en/docs/topics/registries.md
Labels: size/XS
