Repository helm/helm-www, pull requests merged in 2021-03, with the labels that each got.

#1031 Fix console output
  content/en/docs/chart_template_guide/values_files.md
  content/ko/docs/chart_template_guide/values_files.md
  content/zh/docs/chart_template_guide/values_files.md
Labels: size/M

#1034 Adding blog on 2nd security audit
  content/en/blog/2021-03-05-second-security-audit/arch.png
  content/en/blog/2021-03-05-second-security-audit/index.md
Labels: size/S

#1035 Fix typo
  content/en/docs/chart_template_guide/control_structures.md
  content/en/docs/chart_template_guide/function_list.md
  content/en/docs/chart_template_guide/variables.md
Labels: size/XS

#1029 [ru] Added Russian lang
  config.toml
  content/ru/docs/_index.md
  content/ru/docs/intro/_index.md
  content/ru/docs/intro/install.md
  content/ru/docs/intro/quickstart.md
  content/ru/docs/intro/using_helm.md
  i18n/ru.toml
Labels: size/XXL

#1038 Fix menu in Edge and Chrome on Windows
  themes/helm/assets/js/foundation.js
Labels: size/XS

#1037 Update charts.md
  content/en/docs/topics/charts.md
Labels: size/XS

#1040 Fixed Typo
  content/ko/docs/topics/charts.md
Labels: size/XS

#1046 Fix link
  content/en/docs/chart_template_guide/helm_ignore_file.md
  content/en/docs/chart_template_guide/wrapping_up.md
  content/ko/docs/chart_template_guide/helm_ignore_file.md
  content/ko/docs/chart_template_guide/wrapping_up.md
  content/zh/docs/chart_template_guide/wrapping_up.md
Labels: size/S

#1042 Fix some typo
  content/en/docs/topics/charts.md
Labels: size/XS

#1045 Change command to remove all files including tests
  content/en/docs/chart_template_guide/subcharts_and_globals.md
Labels: size/XS

#1039 Add kube supported versions for 3.5
  content/en/docs/topics/version_skew.md
Labels: size/XS

#1047 [zh] Add Chinese docs
  content/zh/docs/chart_template_guide/function_list.md
  content/zh/docs/chart_template_guide/getting_started.md
  content/zh/docs/community/history.md
  content/zh/docs/topics/charts.md
Labels: size/S

#1048 [zh] Add Chinese docs
  content/zh/docs/chart_template_guide/subcharts_and_globals.md
  content/zh/docs/community/developers.md
  content/zh/docs/community/localization.md
  content/zh/docs/community/related.md
  content/zh/docs/topics/charts.md
  content/zh/docs/topics/version_skew.md
Labels: size/L

#1053 [ko]add missing ref in quickstart
  content/ko/docs/intro/quickstart.md
Labels: size/XS

#1049 Removing outdated info about branch for Helm 2.
  content/en/docs/community/developers.md
  content/ko/docs/community/developers.md
Labels: size/XS

#1050 [zh] Add Chinese docs
  content/zh/docs/community/developers.md
  content/zh/docs/community/release_checklist.md
Labels: size/L

#1054 Removing current banner that has been up for past 9 months
  i18n/en.toml
  i18n/ja.toml
  i18n/ko.toml
  i18n/ru.toml
  i18n/zh.toml
  themes/helm/layouts/partials/banner.html
Labels: size/S

#1055 Bumping hugo version
  netlify.toml
Labels: size/XS

#1057 Doc/typo ko
  content/ko/docs/chart_best_practices/conventions.md
  content/ko/docs/intro/using_helm.md
Labels: size/S

#1051 French translation
  config.toml
  content/fr/docs/_index.md
  content/fr/docs/intro/_index.md
  content/fr/docs/intro/install.md
  content/fr/docs/intro/quickstart.md
  content/fr/docs/intro/using_helm.md
  i18n/fr.toml
Labels: size/XL
