Repository helm/helm-www, pull requests merged in 2021-01, with the labels that each got.

#946 [ko] Translate community/developer-guide in korean
  content/ko/docs/community/developers.md
Labels: size/L, translation

#990 [ko] update 'helm command : helm' according to changed origin en docs
  content/ko/docs/helm/helm.md
Labels: size/M

#942 [ko] Translate topic/plugins into Korean
  content/ko/docs/topics/plugins.md
Labels: size/L, translation

#1004 Note how secrets end up in the helm storage backend
  content/en/docs/topics/advanced.md
Labels: size/XS

#1001 fix: change semver example
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#1000 docs: refer to Tanka and the helm-tanka plugin
  content/en/docs/community/related.md
Labels: size/XS

#999 docs: Add pre-req for running tests
  content/en/docs/community/developers.md
Labels: awaiting review, size/XS

#1006 Update for v3.5.0 release
  config.toml
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_fish.md
  content/en/docs/helm/helm_completion_zsh.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_env.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_all.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_notes.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_uninstall.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_pull.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_search_hub.md
  content/en/docs/helm/helm_search_repo.md
  content/en/docs/helm/helm_show.md
  content/en/docs/helm/helm_show_all.md
  content/en/docs/helm/helm_show_chart.md
  content/en/docs/helm/helm_show_readme.md
  content/en/docs/helm/helm_show_values.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_uninstall.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
Labels: size/L

#1011 use bitnami/wordpress as the example
  content/en/docs/intro/using_helm.md
Labels: size/L

#1010 Document dependencies from OCI registry
  content/en/docs/topics/registries.md
Labels: size/S

#1005 Add Move2Kube to additional tools
  content/en/docs/community/related.md
Labels: size/XS

#995 [ko] Translate blog/2020-10-30-charts-repo-deprecation into Korean
  content/ko/blog/2020-10-30-charts-repo-deprecation.md
Labels: size/M

#993 [ko] Translate blog/2020-10-26-new-location-stable-incubator-charts into Korean
  content/ko/blog/2020-10-26-new-location-stable-incubator-charts.md
Labels: size/M

#989 [ko] Translate helm command - helm repo into Korean
  content/ko/docs/helm/helm_repo.md
  content/ko/docs/helm/helm_repo_add.md
  content/ko/docs/helm/helm_repo_index.md
  content/ko/docs/helm/helm_repo_list.md
  content/ko/docs/helm/helm_repo_remove.md
  content/ko/docs/helm/helm_repo_update.md
Labels: size/L

#991 [ko] Translate helm command - helm completion into Korean
  content/ko/docs/helm/helm_completion.md
  content/ko/docs/helm/helm_completion_fish.md
Labels: size/M

#985 [ko] Translate helm install of helm command into Korean
  content/ko/docs/helm/helm_install.md
Labels: size/L, translation

#966 [ko] Translate guide/function_list in Korean
  content/ko/docs/chart_template_guide/function_list.md
Labels: size/XXL, translation

#968 [ko] translate helm command - helm list in Korean
  content/ko/docs/helm/helm_list.md
Labels: size/M, translation

#974 [ko] Translate helm command : helm template in Korean
  content/ko/docs/helm/helm_template.md
Labels: size/M, translation

#982 [ko] Translate helm command - helm depedency in Korean
  content/ko/docs/helm/helm_dependency.md
  content/ko/docs/helm/helm_dependency_build.md
  content/ko/docs/helm/helm_dependency_list.md
  content/ko/docs/helm/helm_dependency_update.md
Labels: size/L, translation

#970 [ko] Translate helm-command/helm rollback in Korean
  content/ko/docs/helm/helm_rollback.md
Labels: size/M, translation

#961 [ko] Translate community/release_checklist into Korean
  content/ko/docs/community/release_checklist.md
Labels: size/L, translation

#1009 Update for v3.5.0 and some documents to Chinese
  content/zh/docs/chart_template_guide/data_types.md
  content/zh/docs/chart_template_guide/debugging.md
  content/zh/docs/chart_template_guide/function_list.md
  content/zh/docs/chart_template_guide/functions_and_pipelines.md
  content/zh/docs/chart_template_guide/getting_started.md
  content/zh/docs/chart_template_guide/helm_ignore_file.md
  content/zh/docs/helm/helm.md
  content/zh/docs/helm/helm_completion.md
  content/zh/docs/helm/helm_completion_bash.md
  content/zh/docs/helm/helm_completion_fish.md
  content/zh/docs/helm/helm_completion_zsh.md
  content/zh/docs/helm/helm_create.md
  content/zh/docs/helm/helm_dependency.md
  content/zh/docs/helm/helm_dependency_build.md
  content/zh/docs/helm/helm_dependency_list.md
  content/zh/docs/helm/helm_dependency_update.md
  content/zh/docs/helm/helm_env.md
  content/zh/docs/helm/helm_get.md
  content/zh/docs/helm/helm_get_all.md
  content/zh/docs/helm/helm_get_hooks.md
  content/zh/docs/helm/helm_get_manifest.md
  content/zh/docs/helm/helm_get_notes.md
  content/zh/docs/helm/helm_get_values.md
  content/zh/docs/helm/helm_history.md
  content/zh/docs/helm/helm_install.md
  content/zh/docs/helm/helm_lint.md
  content/zh/docs/helm/helm_list.md
  content/zh/docs/helm/helm_package.md
  content/zh/docs/helm/helm_plugin.md
  content/zh/docs/helm/helm_plugin_install.md
  content/zh/docs/helm/helm_plugin_list.md
  content/zh/docs/helm/helm_plugin_uninstall.md
  content/zh/docs/helm/helm_plugin_update.md
  content/zh/docs/helm/helm_pull.md
  content/zh/docs/helm/helm_repo.md
  content/zh/docs/helm/helm_repo_add.md
  content/zh/docs/helm/helm_repo_index.md
  content/zh/docs/helm/helm_repo_list.md
  content/zh/docs/helm/helm_repo_remove.md
  content/zh/docs/helm/helm_repo_update.md
  content/zh/docs/helm/helm_rollback.md
  content/zh/docs/helm/helm_search.md
  content/zh/docs/helm/helm_search_hub.md
  content/zh/docs/helm/helm_search_repo.md
  content/zh/docs/helm/helm_show.md
  content/zh/docs/helm/helm_show_all.md
  content/zh/docs/helm/helm_show_chart.md
  content/zh/docs/helm/helm_show_readme.md
  content/zh/docs/helm/helm_show_values.md
  content/zh/docs/helm/helm_status.md
  content/zh/docs/helm/helm_template.md
  content/zh/docs/helm/helm_test.md
  content/zh/docs/helm/helm_uninstall.md
  content/zh/docs/helm/helm_upgrade.md
  content/zh/docs/helm/helm_verify.md
  content/zh/docs/helm/helm_version.md
  content/zh/docs/topics/advanced.md
Labels: size/XXL

#959 [ZH] translate docs/intro/using_helm.md into Chinese
  content/zh/docs/intro/using_helm.md
Labels: size/L, translation

#1012 Update references to appVersion
  content/en/docs/topics/charts.md
  content/en/docs/topics/library_charts.md
  content/en/docs/topics/provenance.md
Labels: size/S
