Repository helm/helm-www, pull requests merged in 2021-06, with the labels that each got.

#1121 [zh] Update Chinese docs
  content/zh/docs/helm/helm_completion_fish.md
  content/zh/docs/helm/helm_completion_zsh.md
  content/zh/docs/helm/helm_install.md
  content/zh/docs/helm/helm_list.md
  content/zh/docs/helm/helm_pull.md
  content/zh/docs/helm/helm_show_all.md
  content/zh/docs/helm/helm_show_chart.md
  content/zh/docs/helm/helm_show_readme.md
  content/zh/docs/helm/helm_show_values.md
  content/zh/docs/helm/helm_template.md
  content/zh/docs/helm/helm_upgrade.md
Labels: size/S

#1125 Fix typo
  content/zh/docs/topics/charts.md
Labels: size/XS

#1129 Added install order of resources
  content/en/docs/intro/using_helm.md
Labels: size/M

#1133 Add example on using auto roll deployment checksum with library chart
  content/en/docs/howto/charts_tips_and_tricks.md
Labels: size/XS

#1124 Fixed invalid configmap manifest in the tutorial.
  content/en/docs/chart_template_guide/control_structures.md
Labels: size/S

#1134 Updating for v3.6.1
  config.toml
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_fish.md
  content/en/docs/helm/helm_completion_zsh.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_env.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_all.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_notes.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_uninstall.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_pull.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_search_hub.md
  content/en/docs/helm/helm_search_repo.md
  content/en/docs/helm/helm_show.md
  content/en/docs/helm/helm_show_all.md
  content/en/docs/helm/helm_show_chart.md
  content/en/docs/helm/helm_show_readme.md
  content/en/docs/helm/helm_show_values.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_uninstall.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
Labels: size/L

#1135 Add 3.6.x to version_skew doc
  content/en/docs/topics/version_skew.md
Labels: size/XS

#1136 [zh] Add Chinese docs
  content/zh/docs/chart_template_guide/control_structures.md
  content/zh/docs/helm/helm_install.md
  content/zh/docs/helm/helm_pull.md
  content/zh/docs/helm/helm_repo_add.md
  content/zh/docs/helm/helm_show_all.md
  content/zh/docs/helm/helm_show_chart.md
  content/zh/docs/helm/helm_show_readme.md
  content/zh/docs/helm/helm_show_values.md
  content/zh/docs/helm/helm_template.md
  content/zh/docs/helm/helm_upgrade.md
  content/zh/docs/howto/charts_tips_and_tricks.md
  content/zh/docs/intro/using_helm.md
Labels: size/M

#1138 Moving Taylor to emeritus
  OWNERS
Labels: size/XS

#1132 Change padding in sidebar toctree items
  themes/helm/assets/sass/docs-sidebar.scss
Labels: size/XS

#1140 fix: typo
  content/zh/docs/topics/charts.md
Labels: size/XS

#1143 added new blog post for Martin
  content/en/blog/2021-06-24-welcome-martin-hickey.md
Labels: size/S

#1144 Fix typo
  content/ko/docs/topics/charts.md
Labels: size/XS

#1146 Updating to 3.6.2
  config.toml
Labels: size/XS

#1147 Adjust docs to add Cloudsmith as a potential chart repository
  content/en/docs/topics/chart_repository.md
Labels: size/XS
