Repository helm/helm-www, pull requests merged in 2022-01, with the labels that each got.

#1256 Blog post announce Karen Chu as Org Maintainer
  content/en/blog/2022-01-11-welcome-karen-chu.md
Labels: blog, size/S

#1253 fix the translation problem
  content/zh/docs/chart_template_guide/yaml_techniques.md
Labels: size/XS

#1265 fix zh translation error about --dry-run code in getting_started.md.
  content/zh/docs/chart_template_guide/builtin_objects.md
  content/zh/docs/chart_template_guide/getting_started.md
Labels: size/M

#1269 fix the issue #1268
  content/zh/docs/topics/kubernetes_distros.md
Labels: size/XS
