Repository helm/helm-www, pull requests merged in 2022-05, with the labels that each got.

#1306 Delay 3.9 release to wait for kubernetes 1.24
  config.toml
Labels: size/XS

#1308 add: examples for --set with [] and null in the using_helm docs.
  content/en/docs/intro/using_helm.md
Labels: size/S

#1311 Fix typo in registries.md
  content/en/docs/topics/registries.md
Labels: size/XS

#1296 docs(install): Update Apt installation in readme
  content/en/docs/intro/install.md
  content/es/docs/intro/install.md
  content/fr/docs/intro/install.md
  content/ja/docs/intro/install.md
  content/pt/docs/intro/install.md
  content/ru/docs/intro/install.md
  content/zh/docs/intro/install.md
Labels: size/M

#1313 Updaing docs for Helm v3.9.0
  config.toml
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_fish.md
  content/en/docs/helm/helm_completion_powershell.md
  content/en/docs/helm/helm_completion_zsh.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_env.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_all.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_notes.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_uninstall.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_pull.md
  content/en/docs/helm/helm_push.md
  content/en/docs/helm/helm_registry.md
  content/en/docs/helm/helm_registry_login.md
  content/en/docs/helm/helm_registry_logout.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_search_hub.md
  content/en/docs/helm/helm_search_repo.md
  content/en/docs/helm/helm_show.md
  content/en/docs/helm/helm_show_all.md
  content/en/docs/helm/helm_show_chart.md
  content/en/docs/helm/helm_show_crds.md
  content/en/docs/helm/helm_show_readme.md
  content/en/docs/helm/helm_show_values.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_uninstall.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
  content/en/docs/topics/version_skew.md
Labels: size/L

#1315 Docs: explain conditional behaviour of 'with'
  content/en/docs/chart_template_guide/control_structures.md
Labels: size/XS
