Repository helm/helm-www, pull requests merged in 2022-02, with the labels that each got.

#1273 fix grammar in chart_best_practices/values.md
  content/en/docs/chart_best_practices/values.md
Labels: size/XS

#1275 content: add helm-mapkubeapis to list of plugins
  content/en/docs/community/related.md
Labels: size/XS

#1276 chinese typo fix
  content/zh/docs/chart_template_guide/builtin_objects.md
Labels: size/XS

#1261 Fix urlJoin documentation output to match input
  content/en/docs/chart_template_guide/function_list.md
  content/ko/docs/chart_template_guide/function_list.md
  content/zh/docs/chart_template_guide/function_list.md
Labels: help wanted, size/XS

#1277 Update Chinese doc
  content/zh/docs/community/related.md
Labels: size/XS

#1278 Adding SUSE logo
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/suse.png
Labels: size/XS

#1284 Blog post announcing storing charts in OCI as a full feature
  content/en/blog/2022-02-28-storing-charts-in-oci.md
Labels: size/L
