Repository helm/helm-www, pull requests merged in 2022-04, with the labels that each got.

#1295 Remove empty space that breaks sigstore link in plugins list
  content/en/docs/community/related.md
Labels: size/XS

#1294 [zh] Add scoop to Chinese doc
  content/zh/docs/intro/install.md
Labels: size/XS

#1297 Bumping to Helm 3.8.2
  config.toml
Labels: size/XS

#1271 Add helm-external-val to the list of helm plugins
  content/en/docs/community/related.md
Labels: size/XS

#1286 docs(helm): update chart_testing.md with new test
  content/en/docs/topics/chart_tests.md
Labels: size/M

#1293 Blog post on tools to manage helm declaratively
  config.toml
  content/en/blog/2022-04-19-tools-to-manage-helm-declaratively.md
  content/en/docs/community/related.md
  themes/helm/assets/sass/docs-content.scss
Labels: blog, size/L

#1300 [zh] Update Chinese docs
  content/zh/docs/community/related.md
  content/zh/docs/topics/chart_tests.md
Labels: size/M

#1250 fix template definition syntax example
  content/en/docs/chart_template_guide/named_templates.md
Labels: help wanted, size/XS

#1302 fix translation errors
  content/zh/docs/topics/registries.md
Labels: size/XS
