Repository helm/helm-www, pull requests merged in 2022-11, with the labels that each got.

#1376 #1375 - Fix FR documentation
  content/fr/docs/_index.md
  content/fr/docs/community/_index.md
  content/fr/docs/howto/_index.md
  content/fr/docs/topics/_index.md
Labels: size/M

#1370 Add Helm Dashboard to the list of plugins
  content/en/docs/community/related.md
Labels: size/XS

#1381 [zh] Update Chinese doc.
  content/zh/docs/community/related.md
Labels: size/XS

#1366 Fix typo in plugin YAML example
  content/en/docs/topics/plugins.md
Labels: bug, size/S

#1384 [zh] Update Chinese doc.
  content/zh/docs/topics/plugins.md
Labels: size/S

#1385 Fix dependencies alignment in zh docs
  content/zh/docs/helm/helm_dependency.md
Labels: size/S

#1386 Add blog post welcoming yxxhero
  content/en/blog/2022-11-14-welcome-yxxhero.md
Labels: size/S

#1374 Fix active link in sidebar
  themes/helm/assets/js/app.js
Labels: size/XS

#1309 Adding toYaml docs
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS

#1396 [zh] Update Chinese doc
  content/zh/docs/chart_template_guide/function_list.md
Labels: size/XS

#1397 Adding helm-release plugin
  content/en/docs/community/related.md
Labels: size/XS

#1392 Improve helmignore docu
  content/en/docs/chart_template_guide/helm_ignore_file.md
Labels: size/XS

#1382 Spanish translation of the file chart_releaser_action.md
  content/es/docs/howto/chart_releaser_action.md
Labels: size/M

#1372 translated best practices labels into japanese
  content/ja/docs/chart_best_practices/labels.md
Labels: size/M

#1359 Add "zot" as OCI-based registry which supports helm charts.
  content/en/docs/topics/registries.md
Labels: size/XS
