Repository helm/helm-www, pull requests merged in 2022-09, with the labels that each got.

#1330 [zh] Update Chinese docs
  content/zh/docs/chart_template_guide/control_structures.md
  content/zh/docs/chart_template_guide/functions_and_pipelines.md
  content/zh/docs/helm/helm_pull.md
  content/zh/docs/helm/helm_template.md
  content/zh/docs/helm/helm_upgrade.md
  content/zh/docs/intro/using_helm.md
  content/zh/docs/topics/version_skew.md
Labels: size/L

#1336 Document fromYaml and fromJson
  content/en/docs/chart_template_guide/function_list.md
Labels: size/M

#1347 helm template renders the chart locally
  content/en/docs/chart_template_guide/debugging.md
Labels: size/XS

#1346 translated best practices dependencies into Japanese.
  content/ja/docs/chart_best_practices/dependencies.md
Labels: size/M

#1285 Update registries.md with additional OCI information
  content/en/docs/topics/registries.md
Labels: size/M

#1356 Updated for the latest Helm release
  config.toml
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_fish.md
  content/en/docs/helm/helm_completion_powershell.md
  content/en/docs/helm/helm_completion_zsh.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_env.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_all.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_notes.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_uninstall.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_pull.md
  content/en/docs/helm/helm_push.md
  content/en/docs/helm/helm_registry.md
  content/en/docs/helm/helm_registry_login.md
  content/en/docs/helm/helm_registry_logout.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_search_hub.md
  content/en/docs/helm/helm_search_repo.md
  content/en/docs/helm/helm_show.md
  content/en/docs/helm/helm_show_all.md
  content/en/docs/helm/helm_show_chart.md
  content/en/docs/helm/helm_show_crds.md
  content/en/docs/helm/helm_show_readme.md
  content/en/docs/helm/helm_show_values.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_uninstall.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
Labels: size/XXL
