Repository helm/helm-www, pull requests merged in 2022-10, with the labels that each got.

#1361 Fixed typo in localization.md
  content/en/docs/community/localization.md
Labels: bug, size/XS

#1354 Update Chinese docs.
  content/zh/docs/chart_template_guide/debugging.md
  content/zh/docs/chart_template_guide/function_list.md
  content/zh/docs/intro/install.md
  content/zh/docs/topics/charts.md
  content/zh/docs/topics/kubernetes_distros.md
Labels: size/M

#1363 Doc : typo in online documentation
  content/en/docs/chart_template_guide/control_structures.md
  content/ko/docs/chart_template_guide/control_structures.md
Labels: size/XS

#1365 Add blog post on Helm at KubeCon '22
  content/en/blog/2022-10-14-helm-at-kubecon-na-22.md
Labels: size/M

#1368 Update Helm booth heading
  content/en/blog/2022-10-14-helm-at-kubecon-na-22.md
Labels: size/XS

#1367 Update Chinese docs for 3.10.0
  content/zh/docs/helm/helm.md
  content/zh/docs/helm/helm_completion.md
  content/zh/docs/helm/helm_completion_bash.md
  content/zh/docs/helm/helm_completion_fish.md
  content/zh/docs/helm/helm_completion_powershell.md
  content/zh/docs/helm/helm_completion_zsh.md
  content/zh/docs/helm/helm_create.md
  content/zh/docs/helm/helm_dependency.md
  content/zh/docs/helm/helm_dependency_build.md
  content/zh/docs/helm/helm_dependency_list.md
  content/zh/docs/helm/helm_dependency_update.md
  content/zh/docs/helm/helm_env.md
  content/zh/docs/helm/helm_get.md
  content/zh/docs/helm/helm_get_all.md
  content/zh/docs/helm/helm_get_hooks.md
  content/zh/docs/helm/helm_get_manifest.md
  content/zh/docs/helm/helm_get_notes.md
  content/zh/docs/helm/helm_get_values.md
  content/zh/docs/helm/helm_history.md
  content/zh/docs/helm/helm_install.md
  content/zh/docs/helm/helm_lint.md
  content/zh/docs/helm/helm_list.md
  content/zh/docs/helm/helm_package.md
  content/zh/docs/helm/helm_plugin.md
  content/zh/docs/helm/helm_plugin_install.md
  content/zh/docs/helm/helm_plugin_list.md
  content/zh/docs/helm/helm_plugin_uninstall.md
  content/zh/docs/helm/helm_plugin_update.md
  content/zh/docs/helm/helm_pull.md
  content/zh/docs/helm/helm_push.md
  content/zh/docs/helm/helm_registry.md
  content/zh/docs/helm/helm_registry_login.md
  content/zh/docs/helm/helm_registry_logout.md
  content/zh/docs/helm/helm_repo.md
  content/zh/docs/helm/helm_repo_add.md
  content/zh/docs/helm/helm_repo_index.md
  content/zh/docs/helm/helm_repo_list.md
  content/zh/docs/helm/helm_repo_remove.md
  content/zh/docs/helm/helm_repo_update.md
  content/zh/docs/helm/helm_rollback.md
  content/zh/docs/helm/helm_search.md
  content/zh/docs/helm/helm_search_hub.md
  content/zh/docs/helm/helm_search_repo.md
  content/zh/docs/helm/helm_show.md
  content/zh/docs/helm/helm_show_all.md
  content/zh/docs/helm/helm_show_chart.md
  content/zh/docs/helm/helm_show_crds.md
  content/zh/docs/helm/helm_show_readme.md
  content/zh/docs/helm/helm_show_values.md
  content/zh/docs/helm/helm_status.md
  content/zh/docs/helm/helm_template.md
  content/zh/docs/helm/helm_test.md
  content/zh/docs/helm/helm_uninstall.md
  content/zh/docs/helm/helm_upgrade.md
  content/zh/docs/helm/helm_verify.md
  content/zh/docs/helm/helm_version.md
  content/zh/docs/topics/registries.md
Labels: size/XXL

#1371 Fix/docs empty
  content/en/docs/chart_template_guide/function_list.md
  content/ko/docs/chart_template_guide/function_list.md
  content/zh/docs/chart_template_guide/function_list.md
Labels: size/XS
