Repository helm/helm-www, pull requests merged in 2023-04, with the labels that each got.

#1435 google api is forbidden
  content/en/docs/topics/charts.md
Labels: size/XS

#1437 Add documentation for dig
  content/en/docs/chart_template_guide/function_list.md
Labels: size/M

#1433 Chbinousamy patch 1: Added 1 page French doc. Fix Issue #1434
  content/fr/docs/helm/_index.md
  content/fr/docs/helm/helm.md
Labels: size/M

#1451 Update developer guide docs
  content/en/docs/community/developers.md
Labels: size/S

#1421 Spanish translation of docs
  content/es/docs/topics/advanced.md
  content/es/docs/topics/architecture.md
Labels: size/L

#1443 add a simple example for merge function
  content/en/docs/chart_template_guide/function_list.md
Labels: size/S

#1369 [ko] Update korean docs
  content/ko/docs/_index.md
  content/ko/docs/intro/install.md
  content/ko/docs/intro/quickstart.md
Labels: size/L

#1400 Add paragraph about named templates in different chart versions
  content/en/docs/chart_template_guide/named_templates.md
  content/ko/docs/chart_template_guide/named_templates.md
Labels: size/S

#1453 Fix Chinese translation
  content/zh/docs/chart_template_guide/subcharts_and_globals.md
Labels: size/XS

#1452 Spell "Cappuccino" consistently
  content/en/docs/chart_template_guide/yaml_techniques.md
  content/ko/docs/chart_template_guide/yaml_techniques.md
  content/zh/docs/chart_template_guide/yaml_techniques.md
Labels: size/S

#1441 Cheatsheet for Helm
  content/en/docs/intro/CheatSheet.md
Labels: size/L
