Repository helm/helm-www, pull requests merged in 2023-01, with the labels that each got.

#1408 Add release v3.10 version skew
  content/en/docs/topics/version_skew.md
Labels: size/XS

#1411 Fix Chinese translation issue
  content/zh/docs/chart_best_practices/values.md
Labels: size/XS

#1412 [zh] Update Chinese doc.
  content/zh/docs/topics/version_skew.md
Labels: size/XS

#1409 Fixed a type on dependencies.md for korean.
  content/ko/docs/chart_best_practices/dependencies.md
Labels: size/XS

#1410 Translate values_files.md for korean.
  content/ko/docs/chart_template_guide/values_files.md
Labels: size/M

#1402 translated best practices pods into Japanese
  content/ja/docs/chart_best_practices/pods.md
Labels: size/M

#1414 Updating for the release of Helm 3.11.0
  config.toml
  content/en/docs/helm/helm.md
  content/en/docs/helm/helm_completion.md
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_fish.md
  content/en/docs/helm/helm_completion_powershell.md
  content/en/docs/helm/helm_completion_zsh.md
  content/en/docs/helm/helm_create.md
  content/en/docs/helm/helm_dependency.md
  content/en/docs/helm/helm_dependency_build.md
  content/en/docs/helm/helm_dependency_list.md
  content/en/docs/helm/helm_dependency_update.md
  content/en/docs/helm/helm_env.md
  content/en/docs/helm/helm_get.md
  content/en/docs/helm/helm_get_all.md
  content/en/docs/helm/helm_get_hooks.md
  content/en/docs/helm/helm_get_manifest.md
  content/en/docs/helm/helm_get_notes.md
  content/en/docs/helm/helm_get_values.md
  content/en/docs/helm/helm_history.md
  content/en/docs/helm/helm_install.md
  content/en/docs/helm/helm_lint.md
  content/en/docs/helm/helm_list.md
  content/en/docs/helm/helm_package.md
  content/en/docs/helm/helm_plugin.md
  content/en/docs/helm/helm_plugin_install.md
  content/en/docs/helm/helm_plugin_list.md
  content/en/docs/helm/helm_plugin_uninstall.md
  content/en/docs/helm/helm_plugin_update.md
  content/en/docs/helm/helm_pull.md
  content/en/docs/helm/helm_push.md
  content/en/docs/helm/helm_registry.md
  content/en/docs/helm/helm_registry_login.md
  content/en/docs/helm/helm_registry_logout.md
  content/en/docs/helm/helm_repo.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/helm/helm_repo_index.md
  content/en/docs/helm/helm_repo_list.md
  content/en/docs/helm/helm_repo_remove.md
  content/en/docs/helm/helm_repo_update.md
  content/en/docs/helm/helm_rollback.md
  content/en/docs/helm/helm_search.md
  content/en/docs/helm/helm_search_hub.md
  content/en/docs/helm/helm_search_repo.md
  content/en/docs/helm/helm_show.md
  content/en/docs/helm/helm_show_all.md
  content/en/docs/helm/helm_show_chart.md
  content/en/docs/helm/helm_show_crds.md
  content/en/docs/helm/helm_show_readme.md
  content/en/docs/helm/helm_show_values.md
  content/en/docs/helm/helm_status.md
  content/en/docs/helm/helm_template.md
  content/en/docs/helm/helm_test.md
  content/en/docs/helm/helm_uninstall.md
  content/en/docs/helm/helm_upgrade.md
  content/en/docs/helm/helm_verify.md
  content/en/docs/helm/helm_version.md
  content/en/docs/topics/version_skew.md
  content/zh/docs/topics/version_skew.md
Labels: size/L

#1415 Add Botkube to the Community Related page
  content/en/docs/community/related.md
Labels: size/XS

#1417 [zh] Update Chinese docs.
  content/zh/docs/community/related.md
  content/zh/docs/helm/helm_install.md
  content/zh/docs/helm/helm_status.md
  content/zh/docs/helm/helm_template.md
Labels: size/S

#1420 Added JFrog Artifactory as OCI supported registry
  content/en/docs/topics/registries.md
Labels: size/XS

#1423 Add howto reuse chart multiple times in dependency doc
  content/en/docs/helm/helm_dependency.md
Labels: size/S

#1424 [zh] Update Chinese docs.
  content/zh/docs/helm/helm_dependency.md
  content/zh/docs/topics/registries.md
Labels: size/S
