Repository helm/helm-www, pull requests merged in 2024-12, with the labels that each got.

#1658 Helm v3 development now happens on the dev-v3 branch
  content/en/code/helm-v3.md
Labels: size/XS

#1663 Add CRD page(ja)
  content/ja/docs/chart_best_practices/custom_resource_definitions.md
Labels: size/M

#1666 adding new supporter
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/jetbrains.png
Labels: size/M

#1627 feat: Added docs for multi-platform plugin hook support
  content/en/docs/topics/plugins.md
Labels: size/L

#1667 Adding redirect for helm/v4 to the code
  content/en/code/helm-v4.md
Labels: size/XS

#1669 Add plugin `helm-tui`
  content/en/docs/community/related.md
Labels: size/XS
