Repository helm/helm-www, pull requests merged in 2024-10, with the labels that each got.

#1624 Add helm-migrate-values to list of plugins
  content/en/docs/community/related.md
Labels: size/XS

#1592 Fix typo in yaml_techniques.md
  content/en/docs/chart_template_guide/yaml_techniques.md
Labels: size/XS

#1542 Chore: fix Home overview section to show a transparent background color on IOS
  themes/helm/assets/sass/docs-responsive.scss
Labels: size/XS

#1595 Boat bob rides waves more realistically
  themes/helm/assets/sass/helm-boat.scss
Labels: size/XS, design

#1544 Chore: update docs to highlight repo URL
  content/en/docs/intro/using_helm.md
Labels: docs, size/XS

#1634 Remove Weaveworks and Bloodorange, and unused logo images
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/bloodorange.png
  themes/helm/static/img/logowall/codecademy.png
  themes/helm/static/img/logowall/weaveworks.png
Labels: size/XS

#1632 Fix: typo in data_types.md
  content/en/docs/chart_template_guide/data_types.md
Labels: size/XS

#1635 Adding kubecon NA SLC to upcoming events
  config.toml
  i18n/en.toml
Labels: size/XS
