Repository helm/helm-www, pull requests merged in 2024-07, with the labels that each got.

#1597 Road to Helm 4 Blog
  content/en/blog/2024-06-26-the-road-to-helm-4.md
Labels: blog, size/M

#1606 Update 2024-06-26-the-road-to-helm-4.md
  content/en/blog/2024-06-26-the-road-to-helm-4.md
Labels: blog, size/XS

#1596 Docs: Fix typo on the values files page
  content/en/docs/chart_template_guide/values_files.md
Labels: size/XS

#1604 Add blog to announce end of support for Helm 2to3 tool
  content/en/blog/2024-07-16-helm2to3-becomes-unsupported.md
Labels: blog, size/S

#1605 Fix small typo
  content/en/blog/2024-06-26-the-road-to-helm-4.md
Labels: size/XS

#1607 Move hickeyma to emeritus
  OWNERS
Labels: size/XS

#1608 update helm upgrade doc to include --hide-secret that is supported in 3.15.3
  content/en/docs/helm/helm_upgrade.md
Labels: size/XS

#1599 make is clear duration expects a string
  content/en/docs/chart_template_guide/function_list.md
Labels: size/XS
