Repository helm/helm-www, pull requests merged in 2024-02, with the labels that each got.

#1550 Add missing B to 600M
  content/en/docs/intro/using_helm.md
Labels: size/XS

#1547 Fix misleading doc for helm install --dry-run
  content/en/docs/chart_template_guide/debugging.md
Labels: size/XS

#1523 docs(chart_best_practices): callout error with YAML comments
  content/en/docs/chart_best_practices/templates.md
Labels: size/S

#1555 Translation in French of Helm commands
  content/fr/docs/helm/helm.md
  content/fr/docs/helm/helm_completion.md
  content/fr/docs/helm/helm_completion_bash.md
  content/fr/docs/helm/helm_completion_fish.md
  content/fr/docs/helm/helm_completion_powershell.md
  content/fr/docs/helm/helm_completion_zsh.md
  content/fr/docs/helm/helm_create.md
  content/fr/docs/helm/helm_delete.md
  content/fr/docs/helm/helm_dependency.md
  content/fr/docs/helm/helm_dependency_build.md
  content/fr/docs/helm/helm_dependency_list.md
  content/fr/docs/helm/helm_dependency_update.md
  content/fr/docs/helm/helm_env.md
  content/fr/docs/helm/helm_get.md
  content/fr/docs/helm/helm_get_all.md
  content/fr/docs/helm/helm_get_hooks.md
  content/fr/docs/helm/helm_get_manifest.md
  content/fr/docs/helm/helm_get_metadata.md
  content/fr/docs/helm/helm_get_notes.md
  content/fr/docs/helm/helm_get_values.md
  content/fr/docs/helm/helm_history.md
  content/fr/docs/helm/helm_init.md
  content/fr/docs/helm/helm_inspect.md
  content/fr/docs/helm/helm_install.md
  content/fr/docs/helm/helm_lint.md
  content/fr/docs/helm/helm_list.md
  content/fr/docs/helm/helm_package.md
  content/fr/docs/helm/helm_plugin.md
  content/fr/docs/helm/helm_plugin_install.md
  content/fr/docs/helm/helm_plugin_list.md
  content/fr/docs/helm/helm_plugin_uninstall.md
  content/fr/docs/helm/helm_plugin_update.md
  content/fr/docs/helm/helm_pull.md
  content/fr/docs/helm/helm_push.md
  content/fr/docs/helm/helm_registry.md
  content/fr/docs/helm/helm_registry_login.md
  content/fr/docs/helm/helm_registry_logout.md
  content/fr/docs/helm/helm_repo.md
  content/fr/docs/helm/helm_repo_add.md
  content/fr/docs/helm/helm_repo_index.md
  content/fr/docs/helm/helm_repo_list.md
  content/fr/docs/helm/helm_repo_remove.md
  content/fr/docs/helm/helm_repo_update.md
  content/fr/docs/helm/helm_rollback.md
  content/fr/docs/helm/helm_search.md
  content/fr/docs/helm/helm_search_hub.md
  content/fr/docs/helm/helm_search_repo.md
  content/fr/docs/helm/helm_show.md
  content/fr/docs/helm/helm_show_all.md
  content/fr/docs/helm/helm_show_chart.md
  content/fr/docs/helm/helm_show_crds.md
  content/fr/docs/helm/helm_show_readme.md
  content/fr/docs/helm/helm_show_values.md
  content/fr/docs/helm/helm_status.md
  content/fr/docs/helm/helm_template.md
  content/fr/docs/helm/helm_test.md
  content/fr/docs/helm/helm_uninstall.md
  content/fr/docs/helm/helm_upgrade.md
  content/fr/docs/helm/helm_verify.md
  content/fr/docs/helm/helm_version.md
Labels: size/XXL

#1554 docs: Add Subcharts to builtin_objects.md docs
  content/en/docs/chart_template_guide/builtin_objects.md
Labels: size/XS

#1551 Add links to helm-sigstore project
  content/en/docs/topics/provenance.md
  content/en/docs/topics/registries.md
Labels: size/S

#1552 charts_tips_and_tricks.md: remove misleading wording about quotes
  content/en/docs/howto/charts_tips_and_tricks.md
Labels: size/XS

#1557 fix CN document links
  content/zh/docs/chart_template_guide/function_list.md
Labels: size/XS
