Repository helm/helm-www, pull requests merged in 2024-11, with the labels that each got.

#1638 Adding post on kubecon SLC
  content/en/blog/2024-10-07-kubecon-na-24/index.md
  content/en/blog/2024-10-07-kubecon-na-24/kubecon.png
Labels: size/S

#1639 Helm release KubeCon blog
  content/en/blog/2024-11-08-experience-helm-release-kubecon-na-24.md
Labels: size/S

#1640 Use up-to-date Hugo v.0.138
  config.toml
  content/en/blog/2019-09-11-migrate-from-helm-v2-to-helm-v3.md
  content/en/blog/2020-04-30-celebrating-helms-cncf-graduation.md
  content/ko/blog/2020-04-30-celebrating-helms-cncf-graduation.md
  content/ko/docs/faq/_index.md
  netlify.toml
  themes/helm/layouts/partials/css.html
  themes/helm/layouts/partials/js.html
  themes/helm/layouts/partials/nav-i18n.html
Labels: size/M

#1543 Helm SDK doc section and examples
  content/en/docs/community/_index.md
  content/en/docs/faq/_index.md
  content/en/docs/glossary/_index.md
  content/en/docs/sdk/_index.md
  content/en/docs/sdk/examples.md
  content/en/docs/sdk/gosdk.md
  content/en/docs/topics/advanced.md
  layouts/shortcodes/highlightexamplego.html
  sdkexamples/README.md
  sdkexamples/go.mod
  sdkexamples/go.sum
  sdkexamples/install.go
  sdkexamples/list.go
  sdkexamples/main.go
  sdkexamples/pull.go
  sdkexamples/uninstall.go
  sdkexamples/upgrade.go
Labels: docs, size/XXL

#1652 fix: clarify that the repo is a chart repository
  content/en/docs/intro/install.md
Labels: size/XS

#1659 fix typo in provenance.md
  content/en/docs/topics/provenance.md
Labels: size/XS

#1656 fix: get rid of build warning
  themes/helm/layouts/_default/list.html
  themes/helm/layouts/_default/single.html
Labels: size/L
