Repository helm/helm-www, pull requests merged in 2025-07, with the labels that each got.

#1739 Fix typo in the korean docs
  content/ko/docs/community/release_checklist.md
Labels: size/XS

#1731 [ru] fix and translate using_helm.md
  content/ru/docs/intro/using_helm.md
Labels: size/M

#1732 Add RepoFlow to list of supported private Helm registries
  content/en/docs/topics/registries.md
Labels: size/XS

#1729 Generate last docs for 3.18.1
  content/en/docs/helm/helm_completion_bash.md
  content/en/docs/helm/helm_completion_fish.md
  content/en/docs/helm/helm_completion_powershell.md
  content/en/docs/helm/helm_completion_zsh.md
  content/en/docs/helm/helm_registry_login.md
  content/en/docs/helm/helm_repo_add.md
  content/en/docs/topics/version_skew.md
Labels: size/S

#1720 [docs] - toYaml / toYamlPretty
  content/en/docs/chart_template_guide/function_list.md
Labels: size/S

#1580 docs: recommend add `tests/` directory to the `.helmignore`
  content/en/docs/topics/chart_tests.md
Labels: docs, size/XS

#1746 Add gosdk example to zh doc
  content/zh/docs/sdk/_index.md
  content/zh/docs/sdk/examples.md
  content/zh/docs/sdk/gosdk.md
Labels: size/L
