Repository helm/helm-www, pull requests merged in 2025-03, with the labels that each got.

#1699 Update args that will be consumed by the root helm command
  content/en/docs/topics/plugins.md
  content/ko/docs/topics/plugins.md
  content/uk/docs/topics/plugins.md
Labels: size/M

#1694 Add helm-cel plugin to related.md
  content/en/docs/community/related.md
Labels: size/XS

#1691 fix: typo in CheatSheet.md
  content/en/docs/intro/CheatSheet.md
Labels: size/XS

#1695 Fix broken links for sdk examples source
  content/en/docs/sdk/examples.md
  content/uk/docs/sdk/examples.md
Labels: size/XS

#1700 Fix anchor text typo in gosdk.md
  content/en/docs/sdk/gosdk.md
  content/uk/docs/sdk/gosdk.md
Labels: size/XS

#1657 chore: Add build workflow for sdkexamples
  .github/workflows/build.yml
  .gitignore
  Makefile
  sdkexamples/Makefile
Labels: size/M

#1701 [Kr] Translate char_tips docs to Korean
  content/ko/docs/howto/charts_tips_and_tricks.md
Labels: size/S

#1703 Add randBytes to function list
  content/en/docs/chart_template_guide/function_list.md
Labels: size/S

#1704 chore: Run go mod tidy on sdkexamples
  sdkexamples/go.mod
  sdkexamples/go.sum
Labels: size/S

#1709 chore: update sdkexamples for latest helm
  sdkexamples/go.mod
  sdkexamples/go.sum
Labels: size/L
