Repository helm/helm-www, pull requests merged in 2025-01, with the labels that each got.

#1662 clarify global scope meaning for named templates
  content/en/docs/chart_template_guide/named_templates.md
  content/en/docs/chart_template_guide/variables.md
Labels: size/XS

#1654 fix: yaml examples with bad doc separator
  content/en/docs/chart_template_guide/accessing_files.md
  content/en/docs/chart_template_guide/variables.md
Labels: size/XS

#1672 Add Replicated logo
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/replicated.png
Labels: size/XS

#1673 Add Redhat logo
  themes/helm/layouts/partials/footer.html
  themes/helm/static/img/logowall/redhat.png
Labels: size/XS

#1645 chore: remove unused redirects to reduce confusion
  content/code/chartmuseum.md
  content/code/helm-v2.md
  content/code/helm-v3.md
  content/code/helm.md
Labels: size/S

#1670 fix: suggest using registry over repository
  content/en/docs/topics/chart_repository.md
Labels: docs, size/XS

#1636 Adding K8Studio to community related tools
  content/en/docs/community/related.md
  content/zh/docs/community/related.md
Labels: size/XS

#1644 Add Dockerfile and .dockerignore with targets in Makefile
  .dockerignore
  Dockerfile
  Makefile
Labels: size/M

#1661 [uk] add translation Go SDK and examples documentation
  content/uk/docs/_index.md
  content/uk/docs/community/_index.md
  content/uk/docs/community/developers.md
  content/uk/docs/community/history.md
  content/uk/docs/community/release_checklist.md
  content/uk/docs/faq/_index.md
  content/uk/docs/faq/troubleshooting.md
  content/uk/docs/glossary/_index.md
  content/uk/docs/howto/chart_releaser_action.md
  content/uk/docs/intro/install.md
  content/uk/docs/intro/quickstart.md
  content/uk/docs/sdk/_index.md
  content/uk/docs/sdk/examples.md
  content/uk/docs/sdk/gosdk.md
  content/uk/docs/topics/advanced.md
  i18n/uk.toml
Labels: docs, size/L

#1678 chore: update sdkexamples go version
  sdkexamples/go.mod
Labels: size/XS
