Repository helm/helm-www, pull requests merged in 2025-09, with the labels that each got.

#1750 Update instructions for Debian to point to the new repo at Buildkite
  content/en/blog/2025-08-19-debian-helm-repository-move.md
  content/en/docs/intro/install.md
Labels: size/S

#1776 Add gjenkins8 to helm-www OWNERS
  OWNERS
Labels: size/XS

#1779 Fix Korean translations and update Apt installation instructions
  content/ko/docs/intro/install.md
Labels: size/L
